<?php

/**
 * English translations
 * Auto-synced from Vietnamese on 2025-07-20 09:26:44
 */

return array (
  'about' => 
  array (
    'content' => 'About page content',
    'description' => 'Learn about MechaMap',
    'title' => 'About',
  ),
  'active_forums' => 'Active Forums',
  'active_members' => 'Active Members',
  'active_since' => 'Active Since',
  'advanced_search' => 'Advanced Search',
  'all_content' => 'All Content',
  'and' => 'and',
  'approve' => 'Approve',
  'archive' => 'Archive',
  'bookmark' => 'Bookmark',
  'business_development' => 'Business Development',
  'by' => 'by',
  'categories' => 'Categories',
  'chat' => 'Chat',
  'closed' => 'Closed',
  'comment' => 'Comment',
  'community' => 
  array (
    'companies' => 'Companies',
    'description' => 'Connect with the engineering community',
    'events' => 'Events',
    'jobs' => 'Jobs',
    'leaderboard' => 'Leaderboard',
    'members' => 'Members',
    'online_members' => 'Online Members',
    'title' => 'Community',
  ),
  'community_stats' => 'Community Stats',
  'connect_engineers' => 'Connect with 64+ professional engineers',
  'contact' => 'Contact',
  'contributions' => 'contributions',
  'date_created' => 'Date Created',
  'delete' => 'Delete',
  'discussions' => 'discussions',
  'draft' => 'Draft',
  'edit' => 'Edit',
  'engineers' => 'Engineers',
  'error_occurred' => 'An error occurred. Please try again.',
  'errors' => 
  array (
    0 => 
    array (
      'title' => 'Page Not Found',
      'message' => 'The page you are looking for does not exist.',
      'back_home' => 'Back to Home',
    ),
    1 => 
    array (
      'title' => 'Access Denied',
      'message' => 'You do not have permission to access this page.',
    ),
    2 => 
    array (
      'title' => 'Server Error',
      'message' => 'A server error occurred. Please try again later.',
    ),
  ),
  'faq' => 
  array (
    'answer' => 'Answer',
    'description' => 'Common questions and answers',
    'question' => 'Question',
    'title' => 'Frequently Asked Questions',
  ),
  'featured' => 'Featured',
  'featured_content' => 'Featured Content',
  'featured_discussions' => 'Featured Discussions',
  'featured_topics' => 'Featured Topics',
  'filters' => 'Filters',
  'follow' => 'Follow',
  'growth_rate' => 'Growth Rate',
  'help' => 
  array (
    'description' => 'Help center and guides',
    'faq' => 'Frequently Asked Questions',
    'support' => 'Technical Support',
    'title' => 'Help',
    'tutorials' => 'Tutorials',
  ),
  'high_activity' => 'High Activity',
  'in' => 'in',
  'join_community' => 'Join Community',
  'join_discussions' => 'Join 118+ technical discussions',
  'join_engineering_community' => 'Join the leading mechanical engineering community',
  'join_professional_network' => 'Join Professional Network',
  'knowledge' => 
  array (
    'articles' => 'Articles',
    'categories' => 'Categories',
    'description' => 'Technical documentation and knowledge repository',
    'no_results' => 'No results found.',
    'search_placeholder' => 'Search articles...',
    'title' => 'Knowledge Base',
  ),
  'knowledge_hub' => 'Mechanical Knowledge Hub',
  'last_updated' => 'Last Updated',
  'latest_updates' => 'Latest Updates',
  'leaderboard' => 'Leaderboard',
  'like' => 'Like',
  'list' => 'List',
  'load_more' => 'Load More',
  'lock' => 'Lock',
  'logged_in_message' => 'You\'re logged in!',
  'low_activity' => 'Low Activity',
  'mechamap_community' => 'MechaMap Community',
  'medium_activity' => 'Medium Activity',
  'minimize' => 'Minimize',
  'most_liked' => 'Most Liked',
  'most_replied' => 'Most Replied',
  'most_viewed' => 'Most Viewed',
  'new_members' => 'New Members',
  'new_message' => 'New Message',
  'new_this_month' => 'new this month',
  'no_active_members' => 'No active members yet',
  'no_featured_topics' => 'No featured topics yet',
  'no_forums' => 'No forums yet',
  'online_members' => 'Online Members',
  'open' => 'Open',
  'or' => 'or',
  'pages' => 
  array (
    'about_us' => 
    array (
      0 => 'About us',
      1 => 'About Us',
    ),
    'community_rules' => 
    array (
      0 => 'Community rules',
      1 => 'Community Rules',
    ),
    'contact' => 
    array (
      0 => 'Contact',
      1 => 'Contact',
    ),
    'faq' => 'FAQ',
    'guide' => 'Guide',
    'privacy_policy' => 
    array (
      0 => 'Privacy policy',
      1 => 'Privacy Policy',
    ),
    'support' => 'Support',
    'terms_of_service' => 
    array (
      0 => 'Terms of service',
      1 => 'Terms of Service',
    ),
  ),
  'pending' => 'Pending',
  'pin' => 'Pin',
  'points' => 'points',
  'popular_forums' => 'Popular Forums',
  'popular_posts' => 'Popular Posts',
  'privacy' => 
  array (
    'data_collection' => 'Data Collection',
    'data_protection' => 'Data Protection',
    'data_usage' => 'Data Usage',
    'description' => 'User information privacy policy',
    'title' => 'Privacy Policy',
  ),
  'private' => 'Private',
  'processing' => 'Processing...',
  'professional_network' => 'Professional Engineering Network',
  'public' => 'Public',
  'published' => 'Published',
  'quote' => 'Quote',
  'read_less' => 'Read Less',
  'read_more' => 'Read More',
  'recent_activity' => 'Recent Activity',
  'recently' => 'recently',
  'recommendations_for_you' => 'Recommendations for You',
  'reject' => 'Reject',
  'related_communities' => 'Related Communities',
  'reply' => 'Reply',
  'report' => 'Report',
  'restore' => 'Restore',
  'rules' => 
  array (
    'consequences' => 'Violation Consequences',
    'description' => 'Community rules and guidelines',
    'general_rules' => 'General Rules',
    'posting_guidelines' => 'Posting Guidelines',
    'title' => 'Community Rules',
  ),
  'search_in_forum' => 'Search in Forum',
  'search_in_thread' => 'Search in Thread',
  'share' => 'Share',
  'share_experience' => 'Share CAD/CAM/CNC experience',
  'show_less' => 'Show Less',
  'show_more' => 'Show More',
  'showcase_item' => 'Showcase Item',
  'solved' => 'Solved',
  'sort_by' => 'Sort By',
  'sticky' => 'Sticky',
  'subscribe' => 'Subscribe',
  'tags' => 'Tags',
  'technical' => 
  array (
    'cad_library' => 'CAD Library',
    'description' => 'Technical documentation and tools',
    'materials' => 'Materials',
    'processes' => 'Manufacturing Processes',
    'standards' => 'Standards',
    'title' => 'Technical Resources',
  ),
  'technical_discussions' => 'Technical Discussions',
  'terms' => 
  array (
    'description' => 'Terms and conditions of service',
    'last_updated' => 'Last updated',
    'title' => 'Terms of Service',
  ),
  'top_engineers' => 'Top Engineers',
  'topic' => 'topic',
  'topics' => 'topics',
  'total_posts' => 'Total Posts',
  'total_threads' => 'Total Threads',
  'trending_topics' => 'Trending Topics',
  'unfollow' => 'Unfollow',
  'unlike' => 'Unlike',
  'unlock' => 'Unlock',
  'unpin' => 'Unpin',
  'unsolved' => 'Unsolved',
  'unsubscribe' => 'Unsubscribe',
  'unverified' => 'Unverified',
  'verified' => 'Verified',
  'view_all' => 'View All',
  'view_more' => 'View More',
  'weekly_activity' => 'Weekly Activity',
  'weekly_trends' => 'Weekly Trends',
  'welcome' => 'Welcome',
  'community_rules' => 'Community Rules',
  'about_us' => 'About Us',
  'terms_of_service' => 'Terms of Service',
  'privacy_policy' => 'Privacy Policy',
  'back_button' => 'Quay lại [VI]',
  'copied' => 'Đã sao chép! [VI]',
  'copy_link' => 'Copy link',
  'default_description' => 'Chúng tôi đang phát triển tính năng mới thú vị để mang lại trải nghiệm tốt nhất cho cộng đồng kỹ sư cơ khí. [VI]',
  'default_feature' => 'Tính Năng Mới [VI]',
  'default_timeline' => 'Q2 2025 [VI]',
  'email_placeholder' => 'Import email của bạn',
  'explore_forums' => 'Khám phá diễn đàn [VI]',
  'notify_button' => 'Register thông báo',
  'notify_description' => 'Chúng tôi sẽ gửi email thông báo khi tính năng này sẵn sàng. [VI]',
  'notify_success' => 'Đã đăng ký! [VI]',
  'notify_title' => 'Nhận thông báo khi ra mắt [VI]',
  'page_title' => 'Sắp Ra Mắt [VI]',
  'progress_label' => 'Tiến Độ Phát Triển [VI]',
  'share_excitement' => 'Share sự hào hứng của bạn:',
  'share_text' => 'Tính năng mới thú vị sắp ra mắt trên MechaMap! 🚀 [VI]',
  'timeline_title' => 'Thời Gian Dự Kiến [VI]',
  'title' => 'Sắp Ra Mắt [VI]',
);
