<?php

return [
    // Success Messages
    'success' => [
        'created' => 'Tạo thành công!',
        'updated' => 'Cập nhật thành công!',
        'deleted' => 'Xóa thành công!',
        'saved' => 'Lưu thành công!',
        'sent' => 'Gửi thành công!',
        'uploaded' => 'Tải lên thành công!',
        'published' => 'Xuất bản thành công!',
        'approved' => 'Phê duyệt thành công!',
        'activated' => 'Kích hoạt thành công!',
        'deactivated' => 'Vô hiệu hóa thành công!',
        'login' => 'Đăng nhập thành công!',
        'logout' => 'Đăng xuất thành công!',
        'registered' => 'Đăng ký thành công!',
        'verified' => 'Xác minh thành công!',
        'password_reset' => 'Đặt lại mật khẩu thành công!',
        'profile_updated' => 'Cập nhật hồ sơ thành công!',
        'settings_saved' => 'Lưu cài đặt thành công!',
        'email_sent' => 'Email đã được gửi thành công!',
        'payment_successful' => 'Thanh toán thành công!',
        'order_placed' => 'Đặt hàng thành công!',
        'subscription_activated' => 'Kích hoạt đăng ký thành công!',
        'backup_created' => 'Tạo bản sao lưu thành công!',
        'import_completed' => 'Nhập dữ liệu hoàn tất!',
        'export_completed' => 'Xuất dữ liệu hoàn tất!',
    ],
    
    // Error Messages
    'error' => [
        'general' => 'Có lỗi xảy ra. Vui lòng thử lại.',
        'not_found' => 'Không tìm thấy dữ liệu.',
        'unauthorized' => 'Bạn không có quyền thực hiện hành động này.',
        'forbidden' => 'Truy cập bị từ chối.',
        'validation' => 'Dữ liệu không hợp lệ.',
        'server_error' => 'Lỗi máy chủ. Vui lòng thử lại sau.',
        'network_error' => 'Lỗi kết nối mạng.',
        'timeout' => 'Hết thời gian chờ.',
        'file_too_large' => 'Tệp quá lớn.',
        'file_type_invalid' => 'Loại tệp không được hỗ trợ.',
        'upload_failed' => 'Tải lên thất bại.',
        'download_failed' => 'Tải xuống thất bại.',
        'login_failed' => 'Đăng nhập thất bại.',
        'registration_failed' => 'Đăng ký thất bại.',
        'password_incorrect' => 'Mật khẩu không đúng.',
        'email_not_verified' => 'Email chưa được xác minh.',
        'account_disabled' => 'Tài khoản đã bị vô hiệu hóa.',
        'payment_failed' => 'Thanh toán thất bại.',
        'insufficient_funds' => 'Số dư không đủ.',
        'quota_exceeded' => 'Đã vượt quá hạn mức.',
        'rate_limit_exceeded' => 'Quá nhiều yêu cầu. Vui lòng thử lại sau.',
        'maintenance_mode' => 'Hệ thống đang bảo trì.',
        'feature_disabled' => 'Tính năng này đã bị tắt.',
        'database_error' => 'Lỗi cơ sở dữ liệu.',
        'cache_error' => 'Lỗi bộ nhớ đệm.',
        'email_delivery_failed' => 'Gửi email thất bại.',
        'sms_delivery_failed' => 'Gửi SMS thất bại.',
        'backup_failed' => 'Tạo bản sao lưu thất bại.',
        'restore_failed' => 'Khôi phục thất bại.',
        'import_failed' => 'Nhập dữ liệu thất bại.',
        'export_failed' => 'Xuất dữ liệu thất bại.',
    ],
    
    // Warning Messages
    'warning' => [
        'unsaved_changes' => 'Bạn có thay đổi chưa được lưu.',
        'delete_confirmation' => 'Bạn có chắc chắn muốn xóa?',
        'irreversible_action' => 'Hành động này không thể hoàn tác.',
        'data_loss' => 'Dữ liệu có thể bị mất.',
        'session_expiring' => 'Phiên làm việc sắp hết hạn.',
        'low_storage' => 'Dung lượng lưu trữ thấp.',
        'quota_warning' => 'Sắp đạt hạn mức.',
        'password_expiring' => 'Mật khẩu sắp hết hạn.',
        'maintenance_scheduled' => 'Bảo trì hệ thống đã được lên lịch.',
        'browser_compatibility' => 'Trình duyệt có thể không tương thích.',
        'slow_connection' => 'Kết nối mạng chậm.',
        'large_file' => 'Tệp lớn có thể mất thời gian tải.',
        'beta_feature' => 'Đây là tính năng beta.',
        'deprecated_feature' => 'Tính năng này sẽ bị loại bỏ.',
        'security_risk' => 'Có thể có rủi ro bảo mật.',
    ],
    
    // Info Messages
    'info' => [
        'loading' => 'Đang tải...',
        'processing' => 'Đang xử lý...',
        'saving' => 'Đang lưu...',
        'uploading' => 'Đang tải lên...',
        'downloading' => 'Đang tải xuống...',
        'sending' => 'Đang gửi...',
        'connecting' => 'Đang kết nối...',
        'syncing' => 'Đang đồng bộ...',
        'searching' => 'Đang tìm kiếm...',
        'filtering' => 'Đang lọc...',
        'sorting' => 'Đang sắp xếp...',
        'no_data' => 'Không có dữ liệu.',
        'empty_list' => 'Danh sách trống.',
        'no_results' => 'Không có kết quả.',
        'end_of_list' => 'Hết danh sách.',
        'more_available' => 'Còn nhiều hơn nữa.',
        'auto_save' => 'Tự động lưu.',
        'draft_saved' => 'Bản nháp đã được lưu.',
        'offline_mode' => 'Chế độ ngoại tuyến.',
        'online_mode' => 'Chế độ trực tuyến.',
        'sync_required' => 'Cần đồng bộ.',
        'update_available' => 'Có bản cập nhật.',
        'new_version' => 'Phiên bản mới.',
        'feature_coming_soon' => 'Tính năng sắp ra mắt.',
        'under_development' => 'Đang phát triển.',
        'beta_version' => 'Phiên bản beta.',
        'preview_mode' => 'Chế độ xem trước.',
        'read_only' => 'Chỉ đọc.',
        'demo_mode' => 'Chế độ demo.',
    ],
    
    // Confirmation Messages
    'confirm' => [
        'delete' => 'Bạn có chắc chắn muốn xóa mục này?',
        'delete_multiple' => 'Bạn có chắc chắn muốn xóa các mục đã chọn?',
        'logout' => 'Bạn có chắc chắn muốn đăng xuất?',
        'cancel_changes' => 'Bạn có chắc chắn muốn hủy các thay đổi?',
        'reset_form' => 'Bạn có chắc chắn muốn đặt lại biểu mẫu?',
        'clear_data' => 'Bạn có chắc chắn muốn xóa tất cả dữ liệu?',
        'restore_backup' => 'Bạn có chắc chắn muốn khôi phục bản sao lưu?',
        'overwrite_file' => 'Tệp đã tồn tại. Bạn có muốn ghi đè?',
        'leave_page' => 'Bạn có chắc chắn muốn rời khỏi trang này?',
        'close_window' => 'Bạn có chắc chắn muốn đóng cửa sổ?',
        'submit_form' => 'Bạn có chắc chắn muốn gửi biểu mẫu?',
        'publish_content' => 'Bạn có chắc chắn muốn xuất bản nội dung?',
        'archive_item' => 'Bạn có chắc chắn muốn lưu trữ mục này?',
        'activate_feature' => 'Bạn có chắc chắn muốn kích hoạt tính năng này?',
        'deactivate_feature' => 'Bạn có chắc chắn muốn vô hiệu hóa tính năng này?',
    ],
];
