<?php

return [
    'login' => [
        'title' => 'Đăng nhập',
        'email' => 'Email',
        'password' => 'Mật khẩu',
        'remember' => 'Ghi nhớ đăng nhập',
        'forgot_password' => 'Quên mật khẩu?',
        'submit' => 'Đăng nhập',
        'welcome_back' => 'Chào mừng trở lại',
        'email_or_username' => 'Email hoặc tên đăng nhập',
        'or_login_with' => 'Hoặc đăng nhập với',
        'login_with_google' => 'Đăng nhập với Google',
        'login_with_facebook' => 'Đăng nhập với Facebook',
        'dont_have_account' => 'Chưa có tài khoản?',
        'back_to_login' => 'Quay lại đăng nhập',
    ],
    'register' => [
        'title' => 'Đăng ký',
        'name' => 'Họ tên',
        'username' => 'Tên đăng nhập',
        'email' => 'Email',
        'password' => 'Mật khẩu',
        'password_confirmation' => 'Xác nhận mật khẩu',
        'submit' => 'Đăng ký',
        'create_business_account' => 'Tạo tài khoản doanh nghiệp',
    ],

    // Password Reset
    'password' => [
        'forgot_description' => 'Nhập email của bạn để nhận liên kết đặt lại mật khẩu',
        'send_reset_link' => 'Gửi liên kết đặt lại',
    ],

    // Direct auth keys
    'logout' => 'Đăng xuất',

    // Login page specific
    'welcome_back' => 'Chào mừng trở lại!',
    'login_journey_description' => 'Đăng nhập để tiếp tục hành trình kỹ thuật của bạn',
    'email_or_username_label' => 'Email hoặc tên đăng nhập',
    'password_label' => 'Mật khẩu',
    'remember_login' => 'Ghi nhớ đăng nhập',
    'forgot_password_link' => 'Quên mật khẩu?',
    'login_button' => 'Đăng nhập',
    'or_login_with' => 'Hoặc đăng nhập với',
    'login_with_google' => 'Google',
    'login_with_facebook' => 'Facebook',
    'no_account' => 'Chưa có tài khoản?',
    'register_now' => 'Đăng ký ngay',
    'ssl_security' => 'Bảo mật SSL 256-bit',

    // Register page specific
    'create_new_account' => 'Tạo tài khoản mới',
    'welcome_to_mechamap' => 'Chào mừng đến với MechaMap',
    'create_account_journey' => 'Tạo tài khoản để bắt đầu hành trình kỹ thuật của bạn',
    'full_name_label' => 'Họ và tên',
    'full_name_placeholder' => 'Nhập họ và tên đầy đủ của bạn',
    'username_label' => 'Tên đăng nhập',
    'username_placeholder' => 'Chọn tên đăng nhập duy nhất',
    'username_help' => 'Tên đăng nhập sẽ được sử dụng trong URL profile của bạn',
    'email_label' => 'Địa chỉ email',
    'email_placeholder' => 'engineer@company.com',
    'password_placeholder' => 'Tối thiểu 8 ký tự',
    'password_help' => 'Sử dụng ít nhất 8 ký tự với chữ cái, số và ký hiệu',
    'confirm_password_label' => 'Xác nhận mật khẩu',
    'confirm_password_placeholder' => 'Nhập lại mật khẩu',
    'role_label' => 'Vai trò của bạn',
    'role_placeholder' => 'Chọn vai trò phù hợp',
    'register_button' => 'Tạo tài khoản',
    'already_have_account' => 'Đã có tài khoản?',
    'login_here' => 'Đăng nhập tại đây',

    // Community highlights
    'join_community_title' => 'Tham gia cộng đồng kỹ thuật hàng đầu Việt Nam',
    'join_community_description' => 'Khám phá những thảo luận nổi bật và kết nối với các chuyên gia',
    'trending_topics' => 'Xu hướng nổi bật',
    'trending_topics_desc' => 'Mastercam, Siemens PLC, Robot công nghiệp',
    'expert_network' => 'Mạng lưới chuyên gia',
    'expert_network_desc' => '64+ kỹ sư từ các công ty hàng đầu',
    'knowledge_base' => 'Kho tri thức',
    'knowledge_base_desc' => '118+ thảo luận chất lượng cao',

    // Trust indicators
    'trusted_by' => 'Được tin tưởng bởi:',
    'members_badge' => 'Thành viên',
    'individual_partners_badge' => 'Đối tác cá nhân',
    'business_badge' => 'Doanh nghiệp',

    // Content keys for login page
    'knowledge_hub' => 'Nơi hội tụ tri thức cơ khí',
    'connect_engineers' => 'Kết nối với kỹ sư chuyên nghiệp',
    'join_discussions' => 'Tham gia thảo luận kỹ thuật',
    'share_experience' => 'Chia sẻ kinh nghiệm thực tế',
    'marketplace_products' => 'Marketplace sản phẩm kỹ thuật số',
    'join_engineering_community' => 'Tham gia cộng đồng kỹ thuật',

    // Registration wizard keys
    'register' => [
        'step1_title' => 'Đăng ký tài khoản - Bước 1',
        'step2_title' => 'Đăng ký tài khoản - Bước 2',
        'wizard_title' => 'Đăng ký tài khoản MechaMap',
        'step1_subtitle' => 'Bước 1: Thông tin cơ bản',
        'step2_subtitle' => 'Bước 2: Thông tin doanh nghiệp',
        'continue_button' => 'Tiếp tục',
        'back_button' => 'Quay lại',
        'complete_button' => 'Hoàn tất đăng ký',
        'personal_info_title' => 'Thông tin cá nhân',
        'personal_info_description' => 'Vui lòng nhập thông tin cá nhân chính xác để tạo tài khoản của bạn.',
        'account_type_title' => 'Loại tài khoản',
        'account_type_description' => 'Chọn loại tài khoản phù hợp với mục đích sử dụng của bạn.',
        'community_member_title' => 'Thành viên cộng đồng',
        'community_member_description' => 'Dành cho những người muốn tham gia thảo luận và chia sẻ kiến thức',
        'business_partner_title' => 'Đối tác kinh doanh',
        'business_partner_description' => 'Dành cho doanh nghiệp và tổ chức hoạt động trong lĩnh vực cơ khí',
        'member_role' => 'Thành viên',
        'member_role_desc' => 'Tham gia thảo luận, chia sẻ kiến thức và kết nối với cộng đồng cơ khí',
        'guest_role' => 'Đối tác cá nhân',
        'guest_role_desc' => 'Mua bán sản phẩm kỹ thuật số, xem nội dung cộng đồng',
        'manufacturer_role' => 'Nhà sản xuất',
        'manufacturer_role_desc' => 'Sản xuất và cung cấp sản phẩm, thiết bị cơ khí',
        'supplier_role' => 'Nhà cung cấp',
        'supplier_role_desc' => 'Phân phối thiết bị, vật tư và linh kiện cơ khí',
        'brand_role' => 'Nhãn hàng',
        'brand_role_desc' => 'Quảng bá thương hiệu và sản phẩm trong ngành cơ khí',
        'recommended' => 'Khuyến nghị',
        'note_community' => 'Bạn có thể được nâng cấp lên <strong>Thành viên cao cấp</strong> sau khi tích cực tham gia cộng đồng và đóng góp chất lượng.',
        'note_business' => 'Tài khoản doanh nghiệp cần cung cấp thông tin công ty và chờ xác minh từ admin. Sau khi xác minh thành công, bạn có thể được nâng cấp lên <strong>Đối tác đã xác thực</strong>.',
        'terms_agreement' => 'Tôi đồng ý với <a href="#" target="_blank">Điều khoản sử dụng</a> và <a href="#" target="_blank">Chính sách bảo mật</a> của MechaMap',
        'security_note' => 'Thông tin của bạn được bảo mật và mã hóa',
        'already_have_account' => 'Đã có tài khoản?',
        'login_now' => 'Đăng nhập ngay',
        'name_valid' => 'Tên hợp lệ',
        'username_available' => 'Tên đăng nhập khả dụng',
        'email_valid' => 'Email hợp lệ',
        'password_strong' => 'Mật khẩu mạnh',
        'password_match' => 'Mật khẩu khớp',
        'email_help' => 'Email này sẽ được sử dụng để xác minh tài khoản và nhận thông báo',
        'step1_label' => 'Thông tin cơ bản',
        'step2_label' => 'Thông tin doanh nghiệp',
        'step_indicator' => 'Bước :current / :total',
        'progress_complete' => ':percent% hoàn thành',
        'auto_saving' => 'Đang lưu tự động...',
        'account_type_label' => 'Loại tài khoản',
        'company_info_title' => 'Thông tin công ty',
        'company_info_description' => 'Vui lòng cung cấp thông tin chính xác về công ty của bạn để hoàn tất quá trình đăng ký.',
        'company_name_label' => 'Tên công ty',
        'company_name_placeholder' => 'Nhập tên đầy đủ của công ty',
        'company_name_help' => 'Tên công ty phải trùng khớp với giấy phép kinh doanh',
        'tax_code_label' => 'Mã số thuế',
        'tax_code_placeholder' => 'Nhập mã số thuế của công ty',
        'tax_code_help' => 'Mã số thuế sẽ được sử dụng để xác minh doanh nghiệp',
        'business_license_label' => 'Số giấy phép kinh doanh',
        'business_license_placeholder' => 'Nhập số giấy phép kinh doanh',
        'company_address_label' => 'Địa chỉ công ty',
        'company_address_placeholder' => 'Nhập địa chỉ đầy đủ của công ty',
        'company_phone_label' => 'Số điện thoại công ty',
        'company_phone_placeholder' => 'Nhập số điện thoại liên hệ',
        'company_website_label' => 'Website công ty',
        'company_website_placeholder' => 'https://company.com (tùy chọn)',
        'company_description_label' => 'Mô tả về công ty',
        'company_description_placeholder' => 'Mô tả ngắn gọn về hoạt động kinh doanh của công ty',
        'verification_note' => 'Thông tin này sẽ được xác minh bởi admin trước khi tài khoản được kích hoạt.',
        'step2_title' => 'Đăng ký tài khoản - Bước 2',
        'step2_subtitle' => 'Bước 2: Thông tin doanh nghiệp',
        'complete_button' => 'Hoàn tất đăng ký',
        'business_field_label' => 'Lĩnh vực kinh doanh',
        'business_field_help' => 'Chọn ít nhất 1 lĩnh vực, tối đa 5 lĩnh vực',
        'company_description_help' => 'Tối thiểu 50 ký tự, tối đa 1000 ký tự',
        'contact_info_title' => 'Thông tin liên hệ',
        'contact_info_description' => 'Thông tin liên hệ của công ty (không bắt buộc nhưng được khuyến khích).',
        'company_phone' => 'Số điện thoại công ty',
        'company_phone_help' => 'Số điện thoại liên hệ chính của công ty',
        'company_address' => 'Địa chỉ công ty',
        'company_email_label' => 'Email công ty',
        'company_email_placeholder' => 'company@example.com',
        'company_email_help' => 'Email công ty phải khác với email cá nhân',
        'verification_docs_title' => 'Tài liệu xác minh (Tùy chọn)',
        'verification_docs_description' => 'Tải lên các tài liệu để tăng tốc quá trình xác minh tài khoản.',
        'file_upload_title' => 'Kéo thả file vào đây hoặc click để chọn',
        'file_upload_support' => 'Hỗ trợ: PDF, JPG, JPEG, PNG, DOC, DOCX',
        'file_upload_size' => 'Kích thước tối đa: 5MB mỗi file',
        'choose_documents' => 'Chọn tài liệu',
        'document_suggestions' => 'Các tài liệu gợi ý: Giấy phép kinh doanh, Chứng nhận đăng ký thuế, Chứng chỉ chất lượng',
        'important_notes_title' => 'Lưu ý quan trọng',
        'note_verification_required' => 'Tài khoản doanh nghiệp cần được xác minh bởi admin trước khi có thể sử dụng đầy đủ tính năng.',
        'note_verification_time' => 'Quá trình xác minh thường mất 1-3 ngày làm việc.',
        'note_email_notification' => 'Bạn sẽ nhận được email thông báo khi tài khoản được phê duyệt.',
        'note_pending_access' => 'Trong thời gian chờ xác minh, bạn có thể đăng nhập và cập nhật thông tin profile.',
        'back_button' => 'Quay lại',
        'business_categories' => [
            'automotive' => 'Ô tô & Xe máy',
            'aerospace' => 'Hàng không & Vũ trụ',
            'manufacturing' => 'Sản xuất chế tạo',
            'materials' => 'Vật liệu & Kim loại',
            'components' => 'Linh kiện & Phụ tụng',
            'industrial' => 'Thiết bị công nghiệp',
            'electronics' => 'Điện tử & Điện lạnh',
            'energy' => 'Năng lượng & Dầu khí',
            'construction' => 'Xây dựng & Kiến trúc',
            'textiles' => 'Dệt may & Thời trang',
            'food' => 'Thực phẩm & Đồ uống',
            'pharmaceutical' => 'Dược phẩm & Y tế',
            'chemical' => 'Hóa chất & Nhựa',
            'machinery' => 'Máy móc & Thiết bị',
            'tools' => 'Dụng cụ & Công cụ'
        ],
    ],
];
