<?php

/**
 * Following Translation File - English
 */

return [
  'following' => 'Following',
  'followers' => 'Followers',
  'followed_threads' => 'Followed Threads',
  'participated_discussions' => 'Participated Discussions',
  'filters' => 'Filters',
  'people_following_you' => 'People Following You',
  'people_you_follow' => 'People You Follow',
  'follow' => 'Follow',
  'following' => 'Following',
  'followers' => 'Followers',
  'followed_threads' => 'Followed Threads',
  'participated_discussions' => 'Participated Discussions',
  'filters' => 'Filters',
  'all_forums' => 'All Forums',
  'unfollow' => 'Unfollow',
  'not_watching_threads' => 'You are not watching any threads.',
  'follow_threads_to_see' => 'Follow threads to see them here.',
  'people_following_you' => 'People Following You',
  'unfollow' => 'Unfollow',
  'follow' => 'Follow',
  'no_followers_yet' => 'You don\'t have any followers yet.',
  'followers_will_appear_here' => 'When someone follows you, they will appear here.',
  'people_you_follow' => 'People You Follow',
  'not_following_anyone' => 'You are not following anyone yet.',
  'follow_users_to_see_updates' => 'Follow other users to see their updates in your feed.',
  'following' => 'Following',
  'followers' => 'Followers',
  'followed_threads' => 'Followed Threads',
  'participated_discussions' => 'Participated Discussions',
  'filters' => 'Filters',
  'all_forums' => 'All Forums',
  'unfollow' => 'Unfollow',
  'follow' => 'Follow',
  'not_watching_any_threads' => 'You are not watching any threads.',
  'follow_threads_to_see_here' => 'Follow threads to see them here.',
  'people_following_you' => 'People Following You',
  'no_followers_yet' => 'You don\'t have any followers yet.',
  'when_someone_follows_you' => 'When someone follows you, they will appear here.',
  'people_you_follow' => 'People You Follow',
  'not_following_anyone_yet' => 'You are not following anyone yet.',
  'follow_other_users_to_see_updates' => 'Follow other users to see their updates in your feed.',
  'join_conversation_help' => 'Join the conversation by commenting on threads.',
];
