<?php

/**
 * Gallery Translation File - English
 */

return [
  'search_placeholder' => 'Search gallery...',
  'uploaded_by' => 'Uploaded by',
  'by' => 'By',
  'no_media_found' => 'No media items found',
  'upload_media' => 'Upload Media',
  'select_file' => 'Select File',
  'title' => 'Title',
  'title_help' => 'Give your media a descriptive title (optional)',
  'description' => 'Description',
  'description_help' => 'Add a description for your media (optional)',
  'upload' => 'Upload',
  'comments' => 'Comments',
  'comments_coming_soon' => 'Comments feature coming soon',
  'media_information' => 'Media Information',
  'uploaded' => 'Uploaded',
  'description' => 'Description',
  'comments' => 'Comments',
  'comments_coming_soon' => 'Comments feature coming soon.',
  'media_information' => 'Media Information',
  'uploaded' => 'Uploaded',
  'file_name' => 'File Name',
  'file_type' => 'File Type',
  'file_size' => 'File Size',
  'dimensions' => 'Dimensions',
  'unknown' => 'Unknown',
  'download' => 'Download',
  'delete_confirm' => 'Are you sure you want to delete this media?',
  'delete' => 'Delete',
  'share' => 'Share',
  'check_out_image' => 'Check out this image',
  'url_copied' => 'URL copied to clipboard!',
  'select_file' => 'Select File',
  'title' => 'Title',
  'title_description' => 'Give your media a descriptive title (optional).',
  'description' => 'Description',
  'description_help' => 'Add a description for your media (optional).',
  'upload_media' => 'Upload Media',
  'search_gallery' => 'Search gallery...',
  'uploaded_by' => 'Uploaded by',
  'by' => 'By',
  'no_media_found' => 'No media items found.',
];
