<?php

/**
 * Media Translation File - English (AUTO-GENERATED)
 * Auto-generated from Vietnamese file
 * Auto-updated: 2025-07-22 03:47:48
 */

return array (
  'new' => 'Media mới',
  'images' => 'Hình ảnh',
  'videos' => 'Video',
  'documents' => 'Tài liệu',
  'gallery' => 'Thư viện',
  'upload' => 'Upload',
  'download' => 'Download',
  'view' => 'View',
  'edit' => 'Chỉnh sửa',
  'delete' => 'Delete',
  'share' => 'Share',
  'preview' => 'Preview',
  'thumbnail' => 'Hình thu nhỏ',
  'original' => 'Gốc',
  'size' => 'Kích thước',
  'type' => 'Loại',
  'uploaded' => 'Đã tải lên',
  'created' => 'Đã tạo',
  'modified' => 'Đã sửa đổi',
  'Description' => 'Description',
  'Comments' => 'Comment',
  'Comments feature coming soon.' => 'Tính năng bình luận sẽ sớm ra mắt.',
  'Media Information' => 'Thông tin media',
  'Uploaded' => 'Đã tải lên',
  'File Name' => 'Tên file',
  'File Type' => 'Loại file',
  'File Size' => 'Kích thước file',
  'Dimensions' => 'Kích thước',
  'Unknown' => 'Không xác định',
  'Download' => 'Download',
  'Are you sure you want to delete this media?' => 'Bạn có chắc muốn xóa media này?',
  'Delete' => 'Delete',
  'Share' => 'Share',
  'Check out this image' => 'Xem hình ảnh này',
  'URL copied to clipboard!' => 'URL đã được sao chép vào clipboard!',
  'upload_file' => 'Upload File',
  'choose_file' => 'Choose File',
  'drag_drop' => 'Drag and drop files here',
  'file_size_limit' => 'Maximum file size',
  'allowed_formats' => 'Allowed formats',
  'upload_progress' => 'Upload progress',
  'upload_complete' => 'Upload complete',
  'upload_failed' => 'Upload failed',
  'file_too_large' => 'File too large',
  'invalid_format' => 'Invalid format',
  'no_file_selected' => 'No file selected',
  'replace_file' => 'Replace file',
  'remove_file' => 'Remove file',
  'download_file' => 'Download file',
  'view_file' => 'View file',
  'edit_image' => 'Edit image',
  'crop_image' => 'Crop image',
  'resize_image' => 'Resize image',
  'rotate_image' => 'Rotate image',
  'image_gallery' => 'Image gallery',
  'video_player' => 'Video player',
  'new' => 'New Media',
);
