<?php

/**
 * Translation file
 * Auto-updated: 2025-08-21 06:48:37
 */

return array (
  'main' => 
  array (
    'home' => 
    array (
      0 => 'Home',
      1 => 'Home',
    ),
    'forums' => 
    array (
      0 => 'Forums',
      1 => 'Forums',
    ),
    'marketplace' => 
    array (
      0 => 'Marketplace',
      1 => 'Marketplace',
    ),
    'showcase' => 
    array (
      0 => 'Showcase',
      1 => 'Showcase',
    ),
    'community' => 'Community',
    'more' => 'More',
  ),
  'auth' => 
  array (
    'login' => 
    array (
      0 => 'Login',
      1 => 'Login',
    ),
    'register' => 
    array (
      0 => 'Register',
      1 => 'Register',
    ),
  ),
  'actions' => 
  array (
    'add' => 'Add',
  ),
  'admin' => 
  array (
    'dashboard' => 'Admin Dashboard',
    'user_management' => 'User Management',
    'forum_management' => 'Forum Management',
    'marketplace_management' => 'Marketplace Management',
  ),
  'supplier' => 
  array (
    'dashboard' => 'Dashboard',
    'my_products' => 'My Products',
    'orders' => 'Orders',
    'reports' => 'Reports',
    'product_management' => 'Product Management',
    'my_orders' => 'My Orders',
  ),
  'manufacturer' => 
  array (
    'dashboard' => 'Manufacturer Dashboard',
    'design_management' => 'Design Management',
    'download_orders' => 'Download Orders',
  ),
  'brand' => 
  array (
    'dashboard' => 'Brand Dashboard',
    'market_insights' => 'Market Insights',
    'marketplace_analytics' => 'Marketplace Analytics',
    'promotion_opportunities' => 'Promotion Opportunities',
    'market_analysis' => 'Market Analysis',
  ),
  'sections' => 
  array (
    'search_discovery' => 'Search & Discovery',
    'help_support' => 'Help & Support',
    'about_mechamap' => 'About MechaMap',
  ),
  'pages' => 
  array (
    'photo_gallery' => 'Photo Gallery',
    'browse_by_tags' => 'Browse by Tags',
    'faq' => 'FAQ',
    'help_center' => 'Help Center',
    'contact_support' => 'Contact Support',
    'about_us' => 'About Us',
    'terms_of_service' => 'Terms of Service',
    'privacy_policy' => 'Privacy Policy',
  ),
  'user' => 
  array (
    'messages' => 'Messages',
    'notifications' => 'Notifications',
    'saved' => 'Saved',
    'my_showcase' => 'My Showcase',
    'my_business' => 'My Business',
    'verification_status' => 'Verification Status',
    'my_subscription' => 'My Subscription',
  ),
  'community' => 
  array (
    'quick_access' => 'Quick Access',
    'forum_home_desc' => 'Community forum homepage',
    'popular_topics' => 'Popular Topics',
    'popular_discussions_desc' => 'Most engaging discussions',
    'browse_categories' => 'Browse Categories',
    'explore_topics_desc' => 'Explore topics by category',
    'discover' => 'Discover',
    'recent_discussions' => 'Recent Discussions',
    'recent_discussions_desc' => 'Latest discussions',
    'trending' => 'Trending',
    'trending_desc' => 'Topics gaining attention',
    'most_viewed' => 'Most Viewed',
    'most_viewed_desc' => 'Highly viewed posts',
    'hot_topics' => 'Hot Topics',
    'hot_topics_desc' => 'Active discussion topics',
    'tools_connect' => 'Tools & Connect',
    'member_directory' => 'Member Directory',
    'member_directory_desc' => 'Find and connect with members',
    'events_webinars' => 'Events & Webinars',
    'events_webinars_desc' => 'Join community events',
    'job_board' => 'Job Board',
    'job_board_desc' => 'Find career opportunities',
  ),
  'add_menu' => 
  array (
    'create_content' => 
    array (
      'title' => 'Create New Content',
      'new_thread' => 'Start Discussion',
      'new_thread_desc' => 'Ask questions, share knowledge',
      'new_showcase' => 'Share Project',
      'new_showcase_desc' => 'Show off your engineering work',
      'upload_photo' => 'Upload Photos',
      'upload_photo_desc' => 'Share engineering images',
      'add_product' => 'List Product',
      'add_product_desc' => 'Sell your products',
      'become_seller' => 'Become Seller',
      'become_seller_desc' => 'Start selling on marketplace',
      'create_document' => 'Create Document',
      'create_document_desc' => 'Share technical documents',
    ),
    'discovery' => 
    array (
      'title' => 'Search & Discovery',
      'advanced_search' => 'Advanced Search',
      'advanced_search_desc' => 'Find exactly what you need',
      'browse_tags' => 'Browse by Tags',
      'browse_tags_desc' => 'Explore topics by category',
      'community_stats' => 'Community Stats',
      'community_stats_desc' => 'Member activity & statistics',
      'tech_trends' => 'Tech Trends',
      'tech_trends_desc' => 'Latest engineering trends',
      'recommendations' => 'Recommendations',
      'recommendations_desc' => 'Personalized content for you',
    ),
    'tools' => 
    array (
      'title' => 'Tools & Utilities',
      'calculator' => 'Engineering Calculator',
      'calculator_desc' => 'Quick calculations & formulas',
      'unit_converter' => 'Unit Converter',
      'unit_converter_desc' => 'Convert between units',
      'material_lookup' => 'Material Database',
      'material_lookup_desc' => 'Properties & specifications',
      'design_tools' => 'Design Tools',
      'design_tools_desc' => 'CAD & design utilities',
      'mobile_app' => 'Mobile App',
      'mobile_app_desc' => 'Access on the go',
      'api_integration' => 'API Integration',
      'api_integration_desc' => 'Developer tools & APIs',
    ),
    'community' => 
    array (
      'title' => 'Community & Support',
      'find_experts' => 'Find Experts',
      'find_experts_desc' => 'Connect with industry experts',
      'business_connect' => 'Business Connect',
      'business_connect_desc' => 'Network with companies',
      'mentorship' => 'Mentorship Program',
      'mentorship_desc' => 'Learn from experienced engineers',
      'job_opportunities' => 'Job Opportunities',
      'job_opportunities_desc' => 'Find engineering jobs',
      'professional_groups' => 'Professional Groups',
      'professional_groups_desc' => 'Join specialized communities',
      'events' => 'Events & Webinars',
      'events_desc' => 'Industry events & workshops',
    ),
    'support' => 
    array (
      'title' => 'Help & Support',
      'faq' => 'FAQ',
      'faq_desc' => 'Frequently asked questions',
      'contact' => 'Contact Support',
      'contact_desc' => 'Get help from our team',
      'about' => 'About MechaMap',
      'about_desc' => 'Learn about our platform',
    ),
    'status' => 
    array (
      'coming_soon' => 'Coming Soon',
      'beta' => 'Beta',
      'new' => 'New',
    ),
    'footer' => 
    array (
      'quick_tip' => 'Quick tip: Use the search to find relevant discussions',
      'keyboard_shortcut' => 'Keyboard shortcut',
      'dark_mode' => 'Dark mode',
    ),
  ),
  'main.community' => 'Community',
  'main.showcase' => 'Showcase',
  'actions.add' => 'Add',
  'main.more' => 'More',
  'sections.search_discovery' => 'Search & Discovery',
  'sections.help_support' => 'Help & Support',
  'sections.about_mechamap' => 'About MechaMap',
  'pages.photo_gallery' => 'Photo Gallery',
  'pages.browse_by_tags' => 'Browse by Tags',
  'pages.faq' => 'FAQ',
  'pages.help_center' => 'Help Center',
  'pages.contact_support' => 'Contact Support',
  'pages.about_us' => 'About Us',
  'pages.terms_of_service' => 'Terms of Service',
  'pages.privacy_policy' => 'Privacy Policy',
  'admin.dashboard' => 'Dashboard',
  'admin.user_management' => 'User Management',
  'admin.forum_management' => 'Forum Management',
  'admin.marketplace_management' => 'Marketplace Management',
  'supplier.dashboard' => 'Dashboard',
  'supplier.my_products' => 'My Products',
  'supplier.orders' => 'Orders',
  'supplier.reports' => 'Reports',
  'supplier.product_management' => 'Product Management',
  'supplier.my_orders' => 'My Orders',
  'brand.dashboard' => 'Dashboard',
  'brand.market_insights' => 'Market Insights',
  'brand.marketplace_analytics' => 'Marketplace Analytics',
  'brand.promotion_opportunities' => 'Promotion Opportunities',
  'brand.market_analysis' => 'Market Analysis',
  'manufacturer.dashboard' => 'Dashboard',
  'manufacturer.design_management' => 'Design Management',
  'manufacturer.download_orders' => 'Download Orders',
  'user.messages' => 'Messages',
  'user.notifications' => 'Notifications',
  'user.saved' => 'Saved',
  'user.my_showcase' => 'My Showcase',
  'user.my_business' => 'My Business',
  'user.verification_status' => 'Verification Status',
  'user.my_subscription' => 'My Subscription',
  'add_menu.create_content.title' => 'Create Content',
  'add_menu.create_content.new_thread' => 'New Thread',
  'add_menu.create_content.new_thread_desc' => 'Start a new discussion in the community',
  'add_menu.create_content.new_showcase' => 'New Showcase',
  'add_menu.create_content.new_showcase_desc' => 'Share your projects and designs',
  'add_menu.create_content.upload_photo' => 'Upload Photo',
  'add_menu.create_content.upload_photo_desc' => 'Share images with the community',
  'add_menu.create_content.add_product' => 'Add Product',
  'add_menu.create_content.add_product_desc' => 'List your product on marketplace',
  'add_menu.create_content.become_seller' => 'Become Seller',
  'add_menu.create_content.become_seller_desc' => 'Register as a seller account',
  'add_menu.create_content.create_document' => 'Create Document',
  'add_menu.create_content.create_document_desc' => 'Write guides or technical documentation',
  'add_menu.discovery.title' => 'Discovery',
  'add_menu.discovery.advanced_search' => 'Advanced Search',
  'add_menu.discovery.advanced_search_desc' => 'Detailed search with filters',
  'add_menu.discovery.browse_tags' => 'Browse Tags',
  'add_menu.discovery.browse_tags_desc' => 'Explore content by topics',
  'add_menu.discovery.community_stats' => 'Community Stats',
  'add_menu.discovery.community_stats_desc' => 'View metrics and trends',
  'add_menu.discovery.tech_trends' => 'Tech Trends',
  'add_menu.discovery.tech_trends_desc' => 'Follow latest technology',
  'add_menu.discovery.recommendations' => 'Recommendations',
  'add_menu.discovery.recommendations_desc' => 'Content recommended for you',
  'add_menu.tools.title' => 'Tools',
  'add_menu.tools.calculator' => 'Calculator',
  'add_menu.tools.calculator_desc' => 'Engineering calculation tools',
  'add_menu.tools.unit_converter' => 'Unit Converter',
  'add_menu.tools.unit_converter_desc' => 'Convert measurement units',
  'add_menu.tools.material_lookup' => 'Material Lookup',
  'add_menu.tools.material_lookup_desc' => 'Find material information',
  'add_menu.tools.design_tools' => 'Design Tools',
  'add_menu.tools.design_tools_desc' => 'Design assistance tools',
  'add_menu.tools.mobile_app' => 'Mobile App',
  'add_menu.tools.mobile_app_desc' => 'Download MechaMap app',
  'add_menu.tools.api_integration' => 'API Integration',
  'add_menu.tools.api_integration_desc' => 'Connect with your systems',
  'add_menu.community.title' => 'Community',
  'add_menu.community.find_experts' => 'Find Experts',
  'add_menu.community.find_experts_desc' => 'Connect with experts',
  'add_menu.community.business_connect' => 'Business Connect',
  'add_menu.community.business_connect_desc' => 'Business networking',
  'add_menu.community.mentorship' => 'Mentorship',
  'add_menu.community.mentorship_desc' => 'Mentorship program',
  'add_menu.community.job_opportunities' => 'Job Opportunities',
  'add_menu.community.job_opportunities_desc' => 'Find industry jobs',
  'add_menu.community.professional_groups' => 'Professional Groups',
  'add_menu.community.professional_groups_desc' => 'Join specialized groups',
  'add_menu.community.events' => 'Events',
  'add_menu.community.events_desc' => 'Industry seminars and events',
  'add_menu.support.title' => 'Support',
  'add_menu.support.faq' => 'FAQ',
  'add_menu.support.faq_desc' => 'Answers to common questions',
  'add_menu.support.contact' => 'Contact',
  'add_menu.support.contact_desc' => 'Contact support team',
  'add_menu.support.about' => 'About Us',
  'add_menu.support.about_desc' => 'Learn about MechaMap',
  'add_menu.status.coming_soon' => 'Coming Soon',
  'add_menu.status.beta' => 'Beta',
  'add_menu.status.new' => 'New',
  'add_menu.footer.quick_tip' => 'Tip: Use shortcuts to create content faster',
  'add_menu.footer.keyboard_shortcut' => 'Create content shortcut',
  'add_menu.footer.dark_mode' => 'Dark mode available in settings',
  'community.quick_access' => 'Quick Access',
  'community.forum_home_desc' => 'Forum home and discussions',
  'community.popular_topics' => 'Popular Topics',
  'community.popular_discussions_desc' => 'Most engaging discussions',
  'community.browse_categories' => 'Browse Categories',
  'community.explore_topics_desc' => 'Explore topics by category',
  'community.discover' => 'Discover',
  'community.recent_discussions' => 'Recent Discussions',
  'community.recent_discussions_desc' => 'Latest community discussions',
  'community.trending' => 'Trending',
  'community.trending_desc' => 'Currently trending content',
  'community.most_viewed' => 'Most Viewed',
  'community.most_viewed_desc' => 'Most viewed content',
  'community.hot_topics' => 'Hot Topics',
  'community.hot_topics_desc' => 'Hotly debated topics',
  'community.tools_connect' => 'Tools & Connect',
  'community.member_directory' => 'Member Directory',
  'community.member_directory_desc' => 'Find and connect with members',
  'community.events_webinars' => 'Events & Webinars',
  'community.events_webinars_desc' => 'Join community events',
  'community.job_board' => 'Job Board',
  'community.job_board_desc' => 'Find career opportunities',
  'nav.main.home' => 'Home',
  'nav.main.forums' => 'Forums',
  'nav.main.marketplace' => 'Marketplace',
  'nav.main.whats_new' => 'What\'s New',
  'auth.login' => 'Login',
  'dashboard' => 'Dashboard',
  'products' => 'Products',
  'orders' => 'Orders',
  'analytics' => 'Analytics',
  'settings' => 'Settings',
  'trending' => 'Trending',
  'most_viewed' => 'Most Viewed',
  'hot_topics' => 'Hot Topics',
);
