<?php

/**
 * Translation file
 * Auto-updated: 2025-08-21 06:48:37
 */

return array (
  'title' => 
  array (
    0 => 'Showcase',
    1 => 'Showcase',
  ),
  'actions' => 
  array (
    'create' => 
    array (
      0 => 'Create Showcase',
      1 => 'Create Showcase',
    ),
    'edit' => 
    array (
      0 => 'Edit Showcase',
      1 => 'Edit Showcase',
    ),
  ),
  'cancel_subscription_anytime' => 'Yes, you can cancel your subscription at any time',
  'custom_enterprise_packages' => 'Yes, we offer custom enterprise packages for larger businesses with specific needs',
  'services_continue_until_billing_end' => 'Your services will continue until the end of your current billing period',
  'max_files_exceeded' => 'Cannot upload more than 10 files',
  'showcase.create_showcase' => 'Create Showcase',
  'showcase.edit_showcase' => 'Edit Showcase',
  'showcase.showcase_title' => 'Showcase Title',
  'showcase.showcase_description' => 'Showcase Description',
  'showcase.showcase_category' => 'Showcase Category',
  'showcase.select_category' => 'Select category',
  'showcase.showcase_tags' => 'Showcase Tags',
  'showcase.add_tags' => 'Add tags',
  'showcase.showcase_images' => 'Showcase Images',
  'showcase.upload_images' => 'Upload images',
  'showcase.showcase_attachments' => 'Attachments',
  'showcase.upload_files' => 'Upload files',
  'showcase.max_files_exceeded' => 'Maximum files exceeded',
  'showcase.file_too_large' => 'File too large',
  'showcase.invalid_file_type' => 'Invalid file type',
  'showcase.view_showcase' => 'View Showcase',
  'showcase.showcase_details' => 'Showcase Details',
  'showcase.created_by' => 'Created by',
  'showcase.created_at' => 'Created at',
  'showcase.updated_at' => 'Updated at',
  'showcase.views_count' => 'Views',
  'showcase.likes_count' => 'Likes',
  'showcase.downloads_count' => 'Downloads',
  'showcase.like_showcase' => 'Like Showcase',
  'showcase.unlike_showcase' => 'Unlike',
  'showcase.share_showcase' => 'Share Showcase',
  'showcase.download_files' => 'Download files',
  'showcase.report_showcase' => 'Report Showcase',
  'showcase.delete_showcase' => 'Delete Showcase',
  'showcase.status.draft' => 'Draft',
  'showcase.status.published' => 'Published',
  'showcase.status.pending' => 'Pending',
  'showcase.status.rejected' => 'Rejected',
  'showcase.title_required' => 'Title is required',
  'showcase.description_required' => 'Description is required',
  'showcase.category_required' => 'Category is required',
  'showcase.images_required' => 'At least one image is required',
  'showcase.created_successfully' => 'Showcase created successfully',
  'showcase.updated_successfully' => 'Showcase updated successfully',
  'showcase.deleted_successfully' => 'Showcase deleted successfully',
  'showcase.no_showcases_found' => 'No showcases found',
  'showcase.save' => 'Save',
  'showcase.cancel' => 'Cancel',
  'showcase.submit' => 'Submit',
  'showcase.publish' => 'Publish',
  'showcase.save_draft' => 'Save Draft',
  'related' => 'Related Showcase',
  'for_thread' => 'for this thread',
  'create_from_thread' => 'Create Showcase from Thread',
  'create_showcase_info' => 'Turn this thread into a professional showcase',
  'create_showcase_button' => 'Create Showcase',
  'create_from_thread_title' => 'Create Showcase from Thread',
  'basic_info' => 'Basic Info',
  'content' => 'Content',
  'complete' => 'Complete',
  'step_1_title' => 'Basic showcase information',
  'showcase_title_help' => 'A concise and attractive title for your showcase',
  'category' => 'Category',
  'project_type' => 'Project type',
  'select_project_type' => 'Select project type',
  'step_2_title' => 'Content and images',
  'project_description' => 'Project description',
  'project_description_help' => 'Detailed description of the project, implementation process and results achieved',
  'cover_image' => 'Cover image',
  'cover_image_help' => 'Main representative image for showcase (16:9 ratio recommended)',
  'current_thread_image' => 'Current thread image',
  'complexity_level' => 'Complexity level',
  'complexity_levels.beginner' => 'Beginner',
  'complexity_levels.intermediate' => 'Intermediate',
  'complexity_levels.advanced' => 'Advanced',
  'complexity_levels.expert' => 'Expert',
  'industry_application' => 'Industry application',
  'industry_placeholder' => 'e.g: Automotive, Aerospace, Construction...',
  'file_attachments' => 'File attachments',
  'file_attachments_optional' => 'optional',
  'file_upload_area' => 'Drag and drop files here or',
  'browse_files' => 'browse files',
  'file_upload_help' => 'Supported: JPG, PNG, PDF, DWG, STEP, STL',
  'file_upload_limits' => 'Maximum 10 files, 50MB each',
  'files_selected' => 'Selected files',
  'file_upload_description' => 'Upload images, technical drawings, CAD files or project-related documents',
  'step_3_title' => 'Confirm and complete',
  'confirm_info' => 'Confirm information',
  'agree_terms' => 'I agree to the terms of use and privacy policy',
  'previous' => 'Previous',
  'next' => 'Next',
  'file_size_error' => 'File size too large (maximum 5MB)',
  'terms_required' => 'Please agree to the terms of use',
  'creating' => 'Creating...',
  'cover_image_required' => 'Please select cover image',
  'public_showcases' => 'Public Showcases',
  'page_description' => 'Discover creative projects from the community',
  'create_new' => 'Create New',
  'project_categories' => 'Project Categories',
  'projects' => 'projects',
  'avg_rating' => 'avg rating',
  'featured_projects' => 'Featured Projects',
  'no_featured_projects' => 'No featured projects yet',
  'advanced_search' => 'Advanced Search',
  'project_name' => 'Project Name',
  'search_placeholder' => 'Enter project name...',
  'all_categories' => 'All Categories',
  'complexity' => 'Complexity',
  'all_levels' => 'All Levels',
  'all_types' => 'All Types',
  'software' => 'Software',
  'all_software' => 'All Software',
  'min_rating' => 'Minimum Rating',
  'all_ratings' => 'All Ratings',
  '4_plus_stars' => '4+ stars',
  '3_plus_stars' => '3+ stars',
  '2_plus_stars' => '2+ stars',
  'search' => 'Search',
  'clear_filters' => 'Clear Filters',
  'sort_by' => 'Sort by',
  'newest' => 'Newest',
  'most_viewed' => 'Most Viewed',
  'highest_rated' => 'Highest Rated',
  'most_downloads' => 'Most Downloads',
  'oldest' => 'Oldest',
  'all_projects' => 'All Projects',
  'results' => 'results',
  'no_projects_found' => 'No projects found',
  'try_different_filters' => 'Try using different filters',
  'create_new_project' => 'Create New Project',
  'showcase_title' => 'Showcase title',
  'select_category' => 'Select category',
  'complexity_levels' => 
  array (
    'beginner' => 'Beginner',
    'intermediate' => 'Intermediate',
    'advanced' => 'Advanced',
    'expert' => 'Expert',
  ),
  'project_types' => 
  array (
    'design_project' => 'Design Project',
    'case_study' => 'Case Study',
    'manufacturing' => 'Manufacturing',
    'analysis_simulation' => 'Analysis & Simulation',
    'research_development' => 'Research & Development',
  ),
  'confirm_points' => 
  array (
    0 => 'Showcase will be created and linked to this thread',
    1 => 'Information will be displayed publicly',
    2 => 'You can edit the showcase after creation',
    3 => 'Showcase will be reviewed before publication',
  ),
  'create_showcase' => 'Create Showcase',
  'title_required' => 'Please enter showcase title',
  'category_required' => 'Please select category',
  'description_required' => 'Please enter project description',
  'file_too_large' => 'File :filename is too large (maximum 50MB)',
  'file_type_not_supported' => 'File type :filename is not supported',
  'new' => 'New Showcases',
  'features.cad' => 'CAD',
  'features.download' => 'Download',
  'ratings' => 'Ratings',
  'show' => 
  array (
    'default_title' => 'Showcase Item',
    'image_alt' => 'Showcase image',
    'share_options' => 'Share options',
    'comment_placeholder' => 'Write your comment...',
    'avatar_alt' => 'Your avatar',
    'user_avatar_alt' => 'Avatar of :name',
    'delete_comment_confirm' => 'Are you sure you want to delete this comment?',
  ),
  'create' => 
  array (
    'title' => 'Create New Showcase',
    'heading' => 'Create New Showcase',
    'description' => 'Share your projects, products or technical achievements with the community',
    'showcase_title' => 'Showcase title',
    'detailed_description' => 'Detailed description',
    'description_placeholder' => 'Detailed description of the project: objectives, technologies used, key features, results achieved...',
    'cover_image_section' => 'Cover Image',
    'upload_cover_image' => 'Upload cover image',
    'cover_image_help' => 'Cover image for your showcase',
    'technical_category' => 'Technical category',
    'choose_category' => 'Choose category',
    'create_button' => 'Create Showcase',
    'close_button' => 'Close',
    'title_placeholder' => 'Showcase title',
    'desc_placeholder' => 'Showcase description...',
    'location_label' => 'Location:',
  ),
);
