<?php

/**
 * Subscription Translation File - English (COMPREHENSIVE)
 * Complete translation coverage for subscription functionality
 * Auto-updated: 2025-07-22 03:55:43
 */

return array (
  'Are you sure you want to cancel your subscription?' => 'Are you sure you want to cancel your subscription?',
  'What Happens When You Cancel' => 'What Happens When You Cancel',
  'You will continue to have access to premium features until the end of your current billing period.' => 'You will continue to have access to premium features until the end of your current billing period.',
  'Your subscription will not renew automatically.' => 'Your subscription will not renew automatically.',
  'You can resubscribe at any time.' => 'You can resubscribe at any time.',
  'Current Subscription Details' => 'Current Subscription Details',
  'Plan' => 'Plan',
  'Status' => 'Status',
  'Billing Period Ends' => 'Billing Period Ends',
  'Price' => 'Price',
  'month' => 'month',
  'Too expensive' => 'Too expensive',
  'Not using the premium features' => 'Not using the premium features',
  'Missing features I need' => 'Missing features I need',
  'Switching to another service' => 'Switching to another service',
  'Other reason' => 'Other reason',
  'Additional feedback (optional)' => 'Additional feedback (optional)',
  'Keep My Subscription' => 'Keep My Subscription',
  'Cancel Subscription' => 'Cancel Subscription',
  'Confirm Cancellation' => 'Confirm Cancellation',
  'Are you absolutely sure you want to cancel your subscription?' => 'Are you absolutely sure you want to cancel your subscription?',
  'You will lose access to premium features at the end of your current billing period.' => 'You will lose access to premium features at the end of your current billing period.',
  'No, Keep My Subscription' => 'No, Keep My Subscription',
  'Yes, Cancel My Subscription' => 'Yes, Cancel My Subscription',
  'subscription' => 'subscription',
  'premium' => 'premium',
  'billing' => 'billing',
  'renewal' => 'renewal',
  'cancel' => 'cancel',
  'upgrade' => 'upgrade',
  'downgrade' => 'downgrade',
  'active' => 'active',
  'expired' => 'expired',
  'cancelled' => 'cancelled',
  'Choose Your Plan' => 'Choose Your Plan',
  'Upgrade your account to unlock premium features and enhance your experience.' => 'Upgrade your account to unlock premium features and enhance your experience.',
  'Current Plan' => 'Current Plan',
  'Expires' => 'Expires',
  'Switch Plan' => 'Switch Plan',
  'Subscribe Now' => 'Subscribe Now',
  'Subscription Benefits' => 'Subscription Benefits',
  'Ad-Free Experience' => 'Ad-Free Experience',
  'Enjoy browsing without any advertisements or distractions.' => 'Enjoy browsing without any advertisements or distractions.',
  'Unlimited Messages' => 'Unlimited Messages',
  'Send unlimited private messages to other users.' => 'Send unlimited private messages to other users.',
  'Premium Badge' => 'Premium Badge',
  'Get a special badge that shows your premium status.' => 'Get a special badge that shows your premium status.',
  'Priority Support' => 'Priority Support',
  'Get faster responses from our support team.' => 'Get faster responses from our support team.',
  'Thank You for Your Subscription!' => 'Thank You for Your Subscription!',
  'Your account has been successfully upgraded.' => 'Your account has been successfully upgraded.',
  'You now have access to all premium features included in your subscription plan.' => 'You now have access to all premium features included in your subscription plan.',
  'Go to Dashboard' => 'Go to Dashboard',
  'View Your Profile' => 'View Your Profile',
  'account_deletion_warning' => 'Once your account is deleted, all of its resources and data will be permanently deleted',
  'no_profile_posts_yet' => 'No profile posts yet',
  'ensure_secure_password' => 'Ensure your account is using a long, random password to stay secure',
  'continue_access_until_billing_end' => 'You will continue to have access to premium features until the end of your current billing period',
  'subscription_will_not_renew' => 'Your subscription will not renew automatically',
  'can_resubscribe_anytime' => 'You can resubscribe at any time',
  'lose_access_at_billing_end' => 'You will lose access to premium features at the end of your current billing period',
  'sorry_to_see_you_go' => 'We\'re Sorry to See You Go',
  'confirm_cancel_question' => 'Are you sure you want to cancel your subscription?',
  'what_happens_when_cancel' => 'What Happens When You Cancel',
  'continue_access_until_end' => 'You will continue to have access to premium features until the end of your current billing period.',
  'no_auto_renewal' => 'Your subscription will not renew automatically.',
  'can_resubscribe_anytime' => 'You can resubscribe at any time.',
  'current_subscription_details' => 'Current Subscription Details',
  'plan' => 'Plan',
  'status' => 'Status',
  'billing_period_ends' => 'Billing Period Ends',
  'price' => 'Price',
  'month' => 'month',
  'tell_us_why_cancelling' => 'Please tell us why you\'re cancelling',
  'too_expensive' => 'Too expensive',
  'not_using_premium_features' => 'Not using the premium features',
  'missing_features_needed' => 'Missing features I need',
  'switching_to_another_service' => 'Switching to another service',
  'other_reason' => 'Other reason',
  'additional_feedback_optional' => 'Additional feedback (optional)',
  'keep_my_subscription' => 'Keep My Subscription',
  'cancel_subscription' => 'Cancel Subscription',
  'confirm_cancellation' => 'Confirm Cancellation',
  'absolutely_sure_cancel' => 'Are you absolutely sure you want to cancel your subscription?',
  'lose_access_premium_features' => 'You will lose access to premium features at the end of your current billing period.',
  'no_keep_subscription' => 'No, Keep My Subscription',
  'yes_cancel_subscription' => 'Yes, Cancel My Subscription',
);
