<?php

/**
 * Following Translation File - Vietnamese
 */

return [
  'following' => 'Đang theo dõi',
  'followers' => 'Người theo dõi',
  'followed_threads' => 'Chủ đề đã theo dõi',
  'participated_discussions' => 'Thảo luận đã tham gia',
  'filters' => 'Bộ lọc',
  'people_following_you' => 'Người đang theo dõi bạn',
  'people_you_follow' => 'Người bạn đang theo dõi',
  'follow' => 'Theo dõi',
  'following' => 'Đang theo dõi',
  'followers' => 'Người theo dõi',
  'followed_threads' => 'Chủ đề đã theo dõi',
  'participated_discussions' => 'Thảo luận đã tham gia',
  'filters' => 'Bộ lọc',
  'all_forums' => 'Tất cả diễn đàn',
  'unfollow' => 'Bỏ theo dõi',
  'not_watching_threads' => 'Bạn không theo dõi chủ đề nào.',
  'follow_threads_to_see' => 'Theo dõi chủ đề để xem chúng ở đây.',
  'people_following_you' => 'Người theo dõi bạn',
  'unfollow' => 'Bỏ theo dõi',
  'follow' => 'Theo dõi',
  'no_followers_yet' => 'Bạn chưa có người theo dõi nào.',
  'followers_will_appear_here' => 'Khi có ai đó theo dõi bạn, họ sẽ xuất hiện ở đây.',
  'people_you_follow' => 'Người bạn theo dõi',
  'not_following_anyone' => 'Bạn chưa theo dõi ai.',
  'follow_users_to_see_updates' => 'Theo dõi người dùng khác để xem cập nhật của họ trong bảng tin của bạn.',
  'following' => 'Đang theo dõi',
  'followers' => 'Người theo dõi',
  'followed_threads' => 'Chủ đề đã theo dõi',
  'participated_discussions' => 'Thảo luận đã tham gia',
  'filters' => 'Bộ lọc',
  'all_forums' => 'Tất cả diễn đàn',
  'unfollow' => 'Bỏ theo dõi',
  'follow' => 'Theo dõi',
  'not_watching_any_threads' => 'Bạn chưa theo dõi chủ đề nào.',
  'follow_threads_to_see_here' => 'Theo dõi chủ đề để xem chúng ở đây.',
  'people_following_you' => 'Những người đang theo dõi bạn',
  'no_followers_yet' => 'Bạn chưa có người theo dõi nào.',
  'when_someone_follows_you' => 'Khi ai đó theo dõi bạn, họ sẽ xuất hiện ở đây.',
  'people_you_follow' => 'Những người bạn theo dõi',
  'not_following_anyone_yet' => 'Bạn chưa theo dõi ai.',
  'follow_other_users_to_see_updates' => 'Theo dõi người dùng khác để xem cập nhật của họ trong nguồn cấp dữ liệu của bạn.',
  'join_conversation_help' => 'Tham gia cuộc trò chuyện bằng cách bình luận về các chủ đề.',
];
