<?php

return [
    // Media types
    'new' => 'Media mới',
    'images' => 'Hình ảnh',
    'videos' => 'Video',
    'documents' => 'Tài liệu',
    'gallery' => 'Thư viện',
    'upload' => 'Tải lên',
    'download' => 'Tải xuống',
    'view' => 'Xem',
    'edit' => 'Chỉnh sửa',
    'delete' => 'Xóa',
    'share' => 'Chia sẻ',
    'preview' => 'Xem trước',
    'thumbnail' => 'Hình thu nhỏ',
    'original' => 'Gốc',
    'size' => 'Kích thước',
    'type' => 'Loại',
    'uploaded' => 'Đã tải lên',
    'created' => 'Đã tạo',
    'modified' => 'Đã sửa đổi',

    // Gallery specific
    'Description' => 'Mô tả',
    'Comments' => 'Bình luận',
    'Comments feature coming soon.' => 'Tính năng bình luận sẽ sớm ra mắt.',
    'Media Information' => 'Thông tin media',
    'Uploaded' => 'Đã tải lên',
    'File Name' => 'Tên file',
    'File Type' => 'Loại file',
    'File Size' => 'Kích thước file',
    'Dimensions' => 'Kích thước',
    'Unknown' => 'Không xác định',
    'Download' => 'Tải xuống',
    'Are you sure you want to delete this media?' => 'Bạn có chắc muốn xóa media này?',
    'Delete' => 'Xóa',
    'Share' => 'Chia sẻ',
    'Check out this image' => 'Xem hình ảnh này',
    'URL copied to clipboard!' => 'URL đã được sao chép vào clipboard!',
  'upload_file' => 'Tải lên tệp',
  'choose_file' => 'Chọn tệp',
  'drag_drop' => 'Kéo thả tệp vào đây',
  'file_size_limit' => 'Kích thước tệp tối đa',
  'allowed_formats' => 'Định dạng cho phép',
  'upload_progress' => 'Tiến trình tải lên',
  'upload_complete' => 'Tải lên hoàn tất',
  'upload_failed' => 'Tải lên thất bại',
  'file_too_large' => 'Tệp quá lớn',
  'invalid_format' => 'Định dạng không hợp lệ',
  'no_file_selected' => 'Chưa chọn tệp',
  'replace_file' => 'Thay thế tệp',
  'remove_file' => 'Xóa tệp',
  'download_file' => 'Tải xuống tệp',
  'view_file' => 'Xem tệp',
  'edit_image' => 'Chỉnh sửa ảnh',
  'crop_image' => 'Cắt ảnh',
  'resize_image' => 'Thay đổi kích thước ảnh',
  'rotate_image' => 'Xoay ảnh',
  'image_gallery' => 'Thư viện ảnh',
  'video_player' => 'Trình phát video',
  'new' => 'Phương tiện mới',
];
