<?php

/**
 * Translation file
 * Auto-updated: 2025-08-21 06:48:37
 */

return array (
  'main' => 
  array (
    'home' => 
    array (
      0 => 'Trang chủ',
      1 => 'Trang chủ',
    ),
    'forums' => 
    array (
      0 => 'Diễn đàn',
      1 => 'Diễn đàn',
    ),
    'marketplace' => 
    array (
      0 => 'Thị trường',
      1 => 'Thị trường',
    ),
    'showcase' => 
    array (
      0 => 'Trưng bày',
      1 => 'Trưng bày',
    ),
    'community' => 'Cộng đồng',
    'more' => 'Thêm',
  ),
  'auth' => 
  array (
    'login' => 
    array (
      0 => 'Đăng nhập',
      1 => 'Đăng nhập',
    ),
    'register' => 
    array (
      0 => 'Đăng ký',
      1 => 'Đăng ký',
    ),
  ),
  'actions' => 
  array (
    'add' => 'Thêm',
  ),
  'dashboard' => 'Bảng điều khiển',
  'products' => 'Sản phẩm',
  'orders' => 'Đơn hàng',
  'analytics' => 'Phân tích',
  'settings' => 'Cài đặt',
  'admin' => 
  array (
    'title' => 'Quản trị',
    'dashboard' => 'Bảng điều khiển Admin',
    'user_management' => 'Quản lý người dùng',
    'forum_management' => 'Quản lý diễn đàn',
    'marketplace_management' => 'Quản lý thị trường',
  ),
  'supplier' => 
  array (
    'dashboard' => 'Bảng điều khiển',
    'my_products' => 'Sản phẩm của tôi',
    'orders' => 'Đơn hàng',
    'reports' => 'Báo cáo',
    'product_management' => 'Quản lý sản phẩm',
    'my_orders' => 'Đơn hàng của tôi',
  ),
  'manufacturer' => 
  array (
    'dashboard' => 'Bảng điều khiển Nhà sản xuất',
    'design_management' => 'Quản lý thiết kế',
    'download_orders' => 'Đơn hàng tải xuống',
  ),
  'brand' => 
  array (
    'dashboard' => 'Bảng điều khiển Thương hiệu',
    'market_insights' => 'Thông tin thị trường',
    'marketplace_analytics' => 'Phân tích thị trường',
    'promotion_opportunities' => 'Cơ hội quảng bá',
    'market_analysis' => 'Phân tích thị trường',
  ),
  'sections' => 
  array (
    'search_discovery' => 'Tìm kiếm & Khám phá',
    'help_support' => 'Trợ giúp & Hỗ trợ',
    'about_mechamap' => 'Về MechaMap',
  ),
  'pages' => 
  array (
    'photo_gallery' => 'Thư viện ảnh',
    'browse_by_tags' => 'Duyệt theo thẻ',
    'faq' => 'Câu hỏi thường gặp',
    'help_center' => 'Trung tâm trợ giúp',
    'contact_support' => 'Liên hệ hỗ trợ',
    'about_us' => 'Về chúng tôi',
    'terms_of_service' => 'Điều khoản dịch vụ',
    'privacy_policy' => 'Chính sách bảo mật',
  ),
  'user' => 
  array (
    'messages' => 'Tin nhắn',
    'notifications' => 'Thông báo',
    'saved' => 'Đã lưu',
    'my_showcase' => 'Showcase của tôi',
    'my_business' => 'Doanh nghiệp của tôi',
    'verification_status' => 'Trạng thái xác minh',
    'my_subscription' => 'Gói đăng ký của tôi',
  ),
  'community' => 
  array (
    'quick_access' => 'Truy cập nhanh',
    'forum_home_desc' => 'Trang chủ diễn đàn cộng đồng',
    'popular_topics' => 'Chủ đề phổ biến',
    'popular_discussions_desc' => 'Các cuộc thảo luận được quan tâm nhất',
    'browse_categories' => 'Duyệt danh mục',
    'explore_topics_desc' => 'Khám phá các chủ đề theo danh mục',
    'discover' => 'Khám phá',
    'recent_discussions' => 'Thảo luận gần đây',
    'recent_discussions_desc' => 'Các cuộc thảo luận mới nhất',
    'trending' => 'Xu hướng',
    'trending_desc' => 'Chủ đề đang được quan tâm',
    'most_viewed' => 'Xem nhiều nhất',
    'most_viewed_desc' => 'Các bài viết có lượt xem cao',
    'hot_topics' => 'Chủ đề nóng',
    'hot_topics_desc' => 'Các chủ đề thảo luận sôi nổi',
    'tools_connect' => 'Công cụ & Kết nối',
    'member_directory' => 'Danh bạ thành viên',
    'member_directory_desc' => 'Tìm kiếm và kết nối với thành viên',
    'events_webinars' => 'Sự kiện & Webinar',
    'events_webinars_desc' => 'Tham gia các sự kiện cộng đồng',
    'job_board' => 'Bảng việc làm',
    'job_board_desc' => 'Tìm kiếm cơ hội nghề nghiệp',
  ),
  'add_menu' => 
  array (
    'create_content' => 
    array (
      'title' => 'Tạo nội dung mới',
      'new_thread' => 'Bắt đầu thảo luận',
      'new_thread_desc' => 'Đặt câu hỏi, chia sẻ kiến thức',
      'new_showcase' => 'Chia sẻ dự án',
      'new_showcase_desc' => 'Khoe công việc kỹ thuật của bạn',
      'upload_photo' => 'Tải lên ảnh',
      'upload_photo_desc' => 'Chia sẻ hình ảnh kỹ thuật',
      'add_product' => 'Đăng sản phẩm',
      'add_product_desc' => 'Bán sản phẩm của bạn',
      'become_seller' => 'Trở thành người bán',
      'become_seller_desc' => 'Bắt đầu bán hàng trên marketplace',
      'create_document' => 'Tạo tài liệu',
      'create_document_desc' => 'Chia sẻ tài liệu kỹ thuật',
    ),
    'discovery' => 
    array (
      'title' => 'Tìm kiếm & Khám phá',
      'advanced_search' => 'Tìm kiếm nâng cao',
      'advanced_search_desc' => 'Tìm chính xác những gì bạn cần',
      'browse_tags' => 'Duyệt theo thẻ',
      'browse_tags_desc' => 'Khám phá chủ đề theo danh mục',
      'community_stats' => 'Thống kê cộng đồng',
      'community_stats_desc' => 'Hoạt động & thống kê thành viên',
      'tech_trends' => 'Xu hướng công nghệ',
      'tech_trends_desc' => 'Xu hướng kỹ thuật mới nhất',
      'recommendations' => 'Đề xuất',
      'recommendations_desc' => 'Nội dung được cá nhân hóa cho bạn',
    ),
    'tools' => 
    array (
      'title' => 'Công cụ & Tiện ích',
      'calculator' => 'Máy tính kỹ thuật',
      'calculator_desc' => 'Tính toán & công thức nhanh',
      'unit_converter' => 'Chuyển đổi đơn vị',
      'unit_converter_desc' => 'Chuyển đổi giữa các đơn vị',
      'material_lookup' => 'Cơ sở dữ liệu vật liệu',
      'material_lookup_desc' => 'Tính chất & thông số kỹ thuật',
      'design_tools' => 'Công cụ thiết kế',
      'design_tools_desc' => 'Tiện ích CAD & thiết kế',
      'mobile_app' => 'Ứng dụng di động',
      'mobile_app_desc' => 'Truy cập mọi lúc mọi nơi',
      'api_integration' => 'Tích hợp API',
      'api_integration_desc' => 'Công cụ & API cho developer',
      'calculators' => 'Máy tính',
      'databases' => 'Cơ sở dữ liệu',
      'libraries' => 'Thư viện',
      'material_calculator' => 'Tính toán vật liệu',
      'process_calculator' => 'Tính toán quy trình',
      'materials_db' => 'Database vật liệu',
      'standards_db' => 'Database tiêu chuẩn',
      'processes_db' => 'Database quy trình',
      'cad_library' => 'Thư viện CAD',
      'technical_resources' => 'Tài nguyên kỹ thuật',
      'documentation' => 'Tài liệu',
    ),
    'community' => 
    array (
      'title' => 'Cộng đồng & Hỗ trợ',
      'find_experts' => 'Tìm chuyên gia',
      'find_experts_desc' => 'Kết nối với chuyên gia ngành',
      'business_connect' => 'Kết nối doanh nghiệp',
      'business_connect_desc' => 'Mạng lưới với các công ty',
      'mentorship' => 'Chương trình cố vấn',
      'mentorship_desc' => 'Học từ kỹ sư giàu kinh nghiệm',
      'job_opportunities' => 'Cơ hội việc làm',
      'job_opportunities_desc' => 'Tìm việc làm kỹ thuật',
      'professional_groups' => 'Nhóm chuyên nghiệp',
      'professional_groups_desc' => 'Tham gia cộng đồng chuyên biệt',
      'events' => 'Sự kiện & Webinar',
      'events_desc' => 'Sự kiện & workshop ngành',
    ),
    'support' => 
    array (
      'title' => 'Trợ giúp & Hỗ trợ',
      'faq' => 'Câu hỏi thường gặp',
      'faq_desc' => 'Các câu hỏi được hỏi thường xuyên',
      'contact' => 'Liên hệ hỗ trợ',
      'contact_desc' => 'Nhận trợ giúp từ đội ngũ của chúng tôi',
      'about' => 'Về MechaMap',
      'about_desc' => 'Tìm hiểu về nền tảng của chúng tôi',
    ),
    'status' => 
    array (
      'coming_soon' => 'Sắp ra mắt',
      'beta' => 'Beta',
      'new' => 'Mới',
    ),
    'footer' => 
    array (
      'quick_tip' => 'Mẹo nhanh: Sử dụng tìm kiếm để tìm các cuộc thảo luận liên quan',
      'keyboard_shortcut' => 'Phím tắt',
      'dark_mode' => 'Chế độ tối',
    ),
  ),
  'main.community' => 'Cộng đồng',
  'main.showcase' => 'Showcase',
  'actions.add' => 'Thêm',
  'main.more' => 'Thêm',
  'sections.search_discovery' => 'Tìm kiếm & Khám phá',
  'sections.help_support' => 'Trợ giúp & Hỗ trợ',
  'sections.about_mechamap' => 'Về MechaMap',
  'pages.photo_gallery' => 'Thư viện ảnh',
  'pages.browse_by_tags' => 'Duyệt theo thẻ',
  'pages.faq' => 'Câu hỏi thường gặp',
  'pages.help_center' => 'Trung tâm trợ giúp',
  'pages.contact_support' => 'Liên hệ hỗ trợ',
  'pages.about_us' => 'Về chúng tôi',
  'pages.terms_of_service' => 'Điều khoản dịch vụ',
  'pages.privacy_policy' => 'Chính sách bảo mật',
  'admin.dashboard' => 'Bảng điều khiển',
  'admin.user_management' => 'Quản lý người dùng',
  'admin.forum_management' => 'Quản lý diễn đàn',
  'admin.marketplace_management' => 'Quản lý marketplace',
  'supplier.dashboard' => 'Bảng điều khiển',
  'supplier.my_products' => 'Sản phẩm của tôi',
  'supplier.orders' => 'Đơn hàng',
  'supplier.reports' => 'Báo cáo',
  'supplier.product_management' => 'Quản lý sản phẩm',
  'supplier.my_orders' => 'Đơn hàng của tôi',
  'brand.dashboard' => 'Bảng điều khiển',
  'brand.market_insights' => 'Thông tin thị trường',
  'brand.marketplace_analytics' => 'Phân tích marketplace',
  'brand.promotion_opportunities' => 'Cơ hội quảng bá',
  'brand.market_analysis' => 'Phân tích thị trường',
  'manufacturer.dashboard' => 'Bảng điều khiển',
  'manufacturer.design_management' => 'Quản lý thiết kế',
  'manufacturer.download_orders' => 'Đơn hàng tải xuống',
  'user.messages' => 'Tin nhắn',
  'user.notifications' => 'Thông báo',
  'user.saved' => 'Đã lưu',
  'user.my_showcase' => 'Showcase của tôi',
  'user.my_business' => 'Doanh nghiệp của tôi',
  'user.verification_status' => 'Trạng thái xác thực',
  'user.my_subscription' => 'Gói đăng ký',
  'add_menu.create_content.title' => 'Tạo nội dung',
  'add_menu.create_content.new_thread' => 'Chủ đề mới',
  'add_menu.create_content.new_thread_desc' => 'Bắt đầu thảo luận mới trong cộng đồng',
  'add_menu.create_content.new_showcase' => 'Showcase mới',
  'add_menu.create_content.new_showcase_desc' => 'Chia sẻ dự án và thiết kế của bạn',
  'add_menu.create_content.upload_photo' => 'Tải ảnh lên',
  'add_menu.create_content.upload_photo_desc' => 'Chia sẻ hình ảnh với cộng đồng',
  'add_menu.create_content.add_product' => 'Thêm sản phẩm',
  'add_menu.create_content.add_product_desc' => 'Đăng sản phẩm lên marketplace',
  'add_menu.create_content.become_seller' => 'Trở thành người bán',
  'add_menu.create_content.become_seller_desc' => 'Đăng ký tài khoản người bán',
  'add_menu.create_content.create_document' => 'Tạo tài liệu',
  'add_menu.create_content.create_document_desc' => 'Viết hướng dẫn hoặc tài liệu kỹ thuật',
  'add_menu.discovery.title' => 'Khám phá',
  'add_menu.discovery.advanced_search' => 'Tìm kiếm nâng cao',
  'add_menu.discovery.advanced_search_desc' => 'Tìm kiếm chi tiết với bộ lọc',
  'add_menu.discovery.browse_tags' => 'Duyệt theo thẻ',
  'add_menu.discovery.browse_tags_desc' => 'Khám phá nội dung theo chủ đề',
  'add_menu.discovery.community_stats' => 'Thống kê cộng đồng',
  'add_menu.discovery.community_stats_desc' => 'Xem số liệu và xu hướng',
  'add_menu.discovery.tech_trends' => 'Xu hướng công nghệ',
  'add_menu.discovery.tech_trends_desc' => 'Theo dõi công nghệ mới nhất',
  'add_menu.discovery.recommendations' => 'Gợi ý',
  'add_menu.discovery.recommendations_desc' => 'Nội dung được đề xuất cho bạn',
  'add_menu.tools.title' => 'Công cụ',
  'add_menu.tools_support.title' => 'Công cụ & Hỗ trợ',
  'add_menu.tools.calculator' => 'Máy tính',
  'add_menu.tools.calculator_desc' => 'Công cụ tính toán kỹ thuật',
  'add_menu.tools.unit_converter' => 'Chuyển đổi đơn vị',
  'add_menu.tools.unit_converter_desc' => 'Chuyển đổi các đơn vị đo lường',
  'add_menu.tools.material_lookup' => 'Tra cứu vật liệu',
  'add_menu.tools.material_lookup_desc' => 'Tìm thông tin về vật liệu',
  'add_menu.tools.design_tools' => 'Công cụ thiết kế',
  'add_menu.tools.design_tools_desc' => 'Công cụ hỗ trợ thiết kế',
  'add_menu.tools.mobile_app' => 'Ứng dụng di động',
  'add_menu.tools.mobile_app_desc' => 'Tải ứng dụng MechaMap',
  'add_menu.tools.api_integration' => 'Tích hợp API',
  'add_menu.tools.api_integration_desc' => 'Kết nối với hệ thống của bạn',
  'add_menu.community.title' => 'Cộng đồng',
  'add_menu.community.find_experts' => 'Tìm chuyên gia',
  'add_menu.community.find_experts_desc' => 'Kết nối với các chuyên gia',
  'add_menu.community.business_connect' => 'Kết nối doanh nghiệp',
  'add_menu.community.business_connect_desc' => 'Mạng lưới doanh nghiệp',
  'add_menu.community.mentorship' => 'Cố vấn',
  'add_menu.community.mentorship_desc' => 'Chương trình cố vấn',
  'add_menu.community.job_opportunities' => 'Cơ hội việc làm',
  'add_menu.community.job_opportunities_desc' => 'Tìm việc làm trong ngành',
  'add_menu.community.professional_groups' => 'Nhóm chuyên nghiệp',
  'add_menu.community.professional_groups_desc' => 'Tham gia nhóm chuyên ngành',
  'add_menu.community.events' => 'Sự kiện',
  'add_menu.community.events_desc' => 'Hội thảo và sự kiện ngành',
  'add_menu.support.title' => 'Hỗ trợ',
  'add_menu.support.faq' => 'Câu hỏi thường gặp',
  'add_menu.support.faq_desc' => 'Câu trả lời cho các thắc mắc',
  'add_menu.support.contact' => 'Liên hệ',
  'add_menu.support.contact_desc' => 'Liên hệ đội ngũ hỗ trợ',
  'add_menu.support.about' => 'Về chúng tôi',
  'add_menu.support.about_desc' => 'Tìm hiểu về MechaMap',
  'add_menu.status.coming_soon' => 'Sắp ra mắt',
  'add_menu.status.beta' => 'Beta',
  'add_menu.status.new' => 'Mới',
  'add_menu.status.ready' => 'Sẵn sàng',
  'add_menu.create_content.create_event' => 'Tạo sự kiện',
  'add_menu.create_content.create_event_desc' => 'Tổ chức sự kiện cho cộng đồng',
  'add_menu.create_content.post_job' => 'Đăng việc làm',
  'add_menu.create_content.post_job_desc' => 'Tuyển dụng nhân tài trong ngành',
  'add_menu.discovery.company_directory' => 'Danh bạ doanh nghiệp',
  'add_menu.discovery.company_directory_desc' => 'Khám phá các công ty trong ngành',
  'add_menu.tools.standards_lookup' => 'Tra cứu tiêu chuẩn',
  'add_menu.tools.standards_lookup_desc' => 'Tìm thông tin về tiêu chuẩn kỹ thuật',
  'add_menu.tools.cad_library' => 'Thư viện CAD',
  'add_menu.tools.cad_library_desc' => 'Tải file CAD và mô hình 3D',
  'add_menu.support.terms' => 'Điều khoản sử dụng',
  'add_menu.support.terms_desc' => 'Quy định và điều khoản của diễn đàn',
  'add_menu.support.privacy' => 'Chính sách bảo mật',
  'add_menu.support.privacy_desc' => 'Cách chúng tôi bảo vệ thông tin của bạn',
  'add_menu.support.rules' => 'Quy tắc cộng đồng',
  'add_menu.support.rules_desc' => 'Nguyên tắc tham gia diễn đàn',
  'add_menu.footer.quick_tip' => 'Mẹo: Sử dụng phím tắt để tạo nội dung nhanh hơn',
  'add_menu.footer.keyboard_shortcut' => 'Phím tắt tạo nội dung',
  'add_menu.footer.dark_mode' => 'Chế độ tối có sẵn trong cài đặt',
  'community.quick_access' => 'Truy cập nhanh',
  'community.forum_home_desc' => 'Trang chủ diễn đàn và thảo luận',
  'community.popular_topics' => 'Chủ đề phổ biến',
  'community.popular_discussions_desc' => 'Các thảo luận được quan tâm nhất',
  'community.browse_categories' => 'Duyệt danh mục',
  'community.explore_topics_desc' => 'Khám phá các chủ đề theo danh mục',
  'community.discover' => 'Khám phá',
  'community.recent_discussions' => 'Thảo luận gần đây',
  'community.recent_discussions_desc' => 'Các cuộc thảo luận mới nhất',
  'community.trending' => 'Xu hướng',
  'community.trending_desc' => 'Nội dung đang thịnh hành',
  'community.most_viewed' => 'Xem nhiều nhất',
  'community.most_viewed_desc' => 'Nội dung được xem nhiều nhất',
  'community.hot_topics' => 'Chủ đề hot',
  'community.hot_topics_desc' => 'Chủ đề đang được thảo luận sôi nổi',
  'community.tools_connect' => 'Công cụ & Kết nối',
  'community.member_directory' => 'Thư mục thành viên',
  'community.member_directory_desc' => 'Tìm và kết nối với thành viên',
  'community.events_webinars' => 'Sự kiện & Webinar',
  'community.events_webinars_desc' => 'Tham gia các sự kiện cộng đồng',
  'community.job_board' => 'Bảng việc làm',
  'community.job_board_desc' => 'Tìm kiếm cơ hội nghề nghiệp',
  'nav.main.home' => 'Trang chủ',
  'nav.main.forums' => 'Diễn đàn',
  'nav.main.marketplace' => 'Thị trường',
  'nav.main.whats_new' => 'Có gì mới',
  'auth.login' => 'Đăng nhập',
  'trending' => 'Xu hướng',
  'most_viewed' => 'Xem nhiều nhất',
  'hot_topics' => 'Chủ đề nóng',
);
