<?php

/**
 * Translation file
 * Auto-updated: 2025-08-21 06:48:37
 */

return array (
  'basic_search' => 'Tìm kiếm cơ bản',
  'search_results' => 'Kết quả tìm kiếm',
  'advanced_search' => 'Tìm kiếm nâng cao',
  'enter_search_terms' => 'Nhập từ khóa tìm kiếm...',
  'search' => 'Tìm kiếm',
  'searching' => 'Đang tìm kiếm...',
  'search_description' => 'Tìm kiếm chủ đề, bài viết, người dùng và nhiều nội dung khác',
  'Search...' => 'Tìm kiếm...',
  'search_placeholder' => 'Tìm kiếm...',
  'All' => 'Tất cả',
  'all' => 'Tất cả',
  'Threads' => 'Chủ đề',
  'threads' => 'Chủ đề',
  'Posts' => 'Bài viết',
  'posts' => 'Bài viết',
  'Users' => 'Người dùng',
  'users' => 'Người dùng',
  'Search results for' => 'Kết quả tìm kiếm cho',
  'search_results_for' => 'Kết quả tìm kiếm cho',
  'Advanced Search' => 'Tìm kiếm nâng cao',
  'By' => 'Bởi',
  'in' => 'trong',
  'Reply in' => 'Phản hồi trong',
  'Joined' => 'Tham gia',
  'No results found for your search.' => 'Không tìm thấy kết quả cho tìm kiếm của bạn.',
  'no_results_found' => 'Không tìm thấy kết quả nào cho tìm kiếm của bạn.',
  'no_results_for' => 'Không tìm thấy kết quả cho',
  'Try different keywords or use the advanced search.' => 'Thử từ khóa khác hoặc sử dụng tìm kiếm nâng cao.',
  'try_different_keywords' => 'Thử sử dụng từ khóa khác hoặc kiểm tra chính tả',
  'try_advanced' => 'THỬ TÌM KIẾM NÂNG CAO',
  'Enter a search term to find content.' => 'Nhập từ khóa để tìm nội dung.',
  'enter_search_term' => 'Nhập từ khóa để tìm kiếm nội dung.',
  'You can search for threads, posts, and users.' => 'Bạn có thể tìm kiếm chủ đề, bài viết và người dùng.',
  'Search Criteria' => 'Tiêu chí tìm kiếm',
  'Keywords' => 'Từ khóa',
  'Author' => 'Tác giả',
  'Forum' => 'Diễn đàn',
  'Unknown' => 'Không xác định',
  'Date Range' => 'Khoảng thời gian',
  'Any' => 'Bất kỳ',
  'to' => 'đến',
  'Present' => 'Hiện tại',
  'Modify Search' => 'Chỉnh sửa tìm kiếm',
  'Sort by' => 'Sắp xếp theo',
  'Descending' => 'Giảm dần',
  'Ascending' => 'Tăng dần',
  'Relevance' => 'Độ liên quan',
  'Date' => 'Ngày',
  'Replies' => 'Phản hồi',
  'replies' => 'Trả lời',
  'views' => 'lượt xem',
  'No threads found matching your search criteria.' => 'Không tìm thấy chủ đề nào phù hợp với tiêu chí tìm kiếm.',
  'No posts found matching your search criteria.' => 'Không tìm thấy bài viết nào phù hợp với tiêu chí tìm kiếm.',
  'all_content' => 'Tất cả nội dung',
  'threads_only' => 'Chỉ chủ đề',
  'posts_only' => 'Chỉ bài viết',
  'users_only' => 'Chỉ người dùng',
  'products_only' => 'Chỉ sản phẩm',
  'showcases_only' => 'Chỉ showcase',
  'documentation_only' => 'Chỉ tài liệu',
  'materials_only' => 'Chỉ vật liệu',
  'cad_files_only' => 'Chỉ tệp CAD',
  'products' => 'Sản phẩm',
  'showcases' => 'Showcase',
  'documentation' => 'Tài liệu',
  'materials' => 'Vật liệu',
  'cad_files' => 'Tệp CAD',
  'found_results' => 'Tìm thấy :count kết quả cho ":query"',
  'view_post' => 'Xem bài viết',
  'no_threads_found' => 'Không tìm thấy chủ đề nào phù hợp với tiêu chí tìm kiếm của bạn.',
  'no_posts_found' => 'Không tìm thấy bài viết nào phù hợp với tiêu chí tìm kiếm của bạn.',
  'no_users_found' => 'Không tìm thấy người dùng nào',
  'no_products_found' => 'Không tìm thấy sản phẩm nào',
  'no_showcases_found' => 'Không tìm thấy showcase nào',
  'no_documentation_found' => 'Không tìm thấy tài liệu nào',
  'no_materials_found' => 'Không tìm thấy vật liệu nào',
  'no_cad_files_found' => 'Không tìm thấy tệp CAD nào',
  'form' => 
  array (
    'placeholder' => 
    array (
      0 => 'Tìm kiếm...',
      1 => 'Tìm kiếm...',
    ),
    'placeholder_detailed' => 'Nhập từ khóa, tên sản phẩm, thương hiệu...',
    'submit' => 'Tìm kiếm',
    'clear' => 'Xóa',
    'filter' => 'Bộ lọc',
    'sort' => 'Sắp xếp',
    'search_button' => 'Tìm kiếm',
    'reset_button' => 'Đặt lại',
  ),
  'results' => 
  array (
    'title' => 
    array (
      0 => 'Kết quả tìm kiếm',
      1 => 'Kết quả tìm kiếm',
    ),
    'no_results' => 
    array (
      0 => 'Không tìm thấy kết quả',
      1 => 'Không tìm thấy kết quả',
    ),
    'showing' => 'Hiển thị :from-:to của :total kết quả',
    'found' => 'Tìm thấy :count kết quả',
    'for_query' => 'cho ":query"',
    'in_category' => 'trong :category',
    'load_more' => 'Tải thêm kết quả',
    'showing_all' => 'Hiển thị tất cả kết quả',
  ),
  'scope' => 
  array (
    'all_content' => 'Tất cả nội dung',
    'in_thread' => 'Trong chủ đề',
    'in_forum' => 'Trong diễn đàn',
    'in_category' => 'Trong danh mục',
    'in_marketplace' => 'Trong marketplace',
    'in_showcase' => 'Trong showcase',
    'global' => 'Toàn bộ hệ thống',
  ),
  'actions' => 
  array (
    'advanced' => 'Tìm kiếm nâng cao',
    'advanced_desc' => 'Tìm kiếm chi tiết với nhiều bộ lọc',
    'save_search' => 'Lưu tìm kiếm',
    'share_results' => 'Chia sẻ kết quả',
    'export_results' => 'Xuất kết quả',
    'view_all' => 'Xem tất cả',
    'view_details' => 'Xem chi tiết',
  ),
  'history' => 
  array (
    'recent' => 'Tìm kiếm gần đây',
    'empty' => 'Chưa có lịch sử tìm kiếm',
    'clear_history' => 'Xóa lịch sử',
    'popular_searches' => 'Tìm kiếm phổ biến',
    'my_searches' => 'Tìm kiếm của tôi',
    'saved_searches' => 'Tìm kiếm đã lưu',
  ),
  'suggestions' => 
  array (
    'popular' => 'Tìm kiếm phổ biến',
    'trending' => 'Xu hướng tìm kiếm',
    'related' => 'Tìm kiếm liên quan',
    'autocomplete' => 'Gợi ý tự động',
    'did_you_mean' => 'Có phải bạn muốn tìm',
    'similar_searches' => 'Tìm kiếm tương tự',
  ),
  'advanced' => 
  array (
    'title' => 'Tìm kiếm nâng cao',
    'description' => 'Sử dụng bộ lọc chi tiết để tìm kiếm chính xác',
    'keywords' => 'Từ khóa',
    'exact_phrase' => 'Cụm từ chính xác',
    'any_words' => 'Bất kỳ từ nào',
    'exclude_words' => 'Loại trừ từ',
    'author' => 'Tác giả',
    'date_range' => 'Khoảng thời gian',
    'category' => 'Danh mục',
    'tags' => 'Thẻ',
    'content_type' => 'Loại nội dung',
    'file_type' => 'Loại file',
    'size_range' => 'Kích thước',
    'price_range' => 'Khoảng giá',
    'rating' => 'Đánh giá',
    'location' => 'Địa điểm',
    'company' => 'Công ty',
    'industry' => 'Ngành nghề',
  ),
  'sort' => 
  array (
    'relevance' => 'Độ liên quan',
    'date_newest' => 'Mới nhất',
    'date_oldest' => 'Cũ nhất',
    'alphabetical' => 'Theo bảng chữ cái',
    'popularity' => 'Phổ biến',
    'rating' => 'Đánh giá',
    'price_low_high' => 'Giá thấp đến cao',
    'price_high_low' => 'Giá cao đến thấp',
    'views' => 'Lượt xem',
    'replies' => 'Phản hồi',
    'downloads' => 'Lượt tải',
  ),
  'filters' => 
  array (
    'all' => 'Tất cả',
    'today' => 'Hôm nay',
    'week' => 'Tuần này',
    'month' => 'Tháng này',
    'year' => 'Năm này',
    'custom_date' => 'Tùy chỉnh ngày',
    'free' => 'Miễn phí',
    'paid' => 'Trả phí',
    'premium' => 'Cao cấp',
    'verified' => 'Đã xác thực',
    'featured' => 'Nổi bật',
    'new' => 'Mới',
    'popular' => 'Phổ biến',
    'trending' => 'Xu hướng',
  ),
  'tips' => 
  array (
    'title' => 'Mẹo tìm kiếm',
    'use_quotes' => 'Sử dụng dấu ngoặc kép để tìm cụm từ chính xác',
    'use_operators' => 'Sử dụng AND, OR, NOT để kết hợp từ khóa',
    'use_wildcards' => 'Sử dụng * để thay thế các ký tự',
    'check_spelling' => 'Kiểm tra chính tả của từ khóa',
    'try_synonyms' => 'Thử sử dụng từ đồng nghĩa',
    'be_specific' => 'Sử dụng từ khóa cụ thể hơn',
  ),
  'errors' => 
  array (
    'empty_query' => 'Vui lòng nhập từ khóa tìm kiếm',
    'too_short' => 'Từ khóa phải có ít nhất 3 ký tự',
    'too_long' => 'Từ khóa không được quá 100 ký tự',
    'invalid_characters' => 'Từ khóa chứa ký tự không hợp lệ',
    'search_failed' => 'Tìm kiếm thất bại, vui lòng thử lại',
    'server_error' => 'Lỗi máy chủ, vui lòng thử lại sau',
  ),
  'stats' => 
  array (
    'total_searches' => 'Tổng số lượt tìm kiếm',
    'popular_keywords' => 'Từ khóa phổ biến',
    'search_trends' => 'Xu hướng tìm kiếm',
    'no_results_rate' => 'Tỷ lệ không có kết quả',
    'average_results' => 'Số kết quả trung bình',
  ),
  'criteria' => 'Tiêu chí tìm kiếm',
  'keywords' => 'Từ khóa',
  'author' => 'Tác giả',
  'forum' => 'Diễn đàn',
  'date_range' => 'Khoảng thời gian',
  'by' => 'Bởi',
  'reply_in' => 'Trả lời trong',
  'joined' => 'Tham gia',
  'form.placeholder' => 'Tìm kiếm...',
  'scope.all_content' => 'Tất cả nội dung',
  'scope.in_thread' => 'Trong chủ đề',
  'scope.in_forum' => 'Trong diễn đàn',
  'actions.advanced' => 'Tìm kiếm nâng cao',
  'history.recent' => 'Tìm kiếm gần đây',
  'history.empty' => 'Chưa có tìm kiếm nào',
  'suggestions.popular' => 'Tìm kiếm phổ biến',
  'basic.search_placeholder' => 'Tìm kiếm chủ đề, bài viết...',
  'basic.search_button' => 'Tìm kiếm',
  'basic.advanced_search' => 'Tìm kiếm nâng cao',
  'basic.recent_searches' => 'Tìm kiếm gần đây',
  'basic.popular_searches' => 'Tìm kiếm phổ biến',
  'basic.search_suggestions' => 'Gợi ý tìm kiếm',
  'basic.no_results' => 'Không tìm thấy kết quả',
  'basic.search_tips' => 'Mẹo tìm kiếm',
  'basic.clear_search' => 'Xóa tìm kiếm',
  'search_tips' => 'Mẹo tìm kiếm',
  'recent_searches' => 'Tìm kiếm gần đây',
  'popular_searches' => 'Tìm kiếm phổ biến',
  'clear_search' => 'Xóa tìm kiếm',
  'search_suggestions' => 'Gợi ý tìm kiếm',
  'no_results' => 'Không có kết quả',
  'advanced_search_link' => 'Tìm kiếm nâng cao',
  'filter_results' => 'Lọc kết quả',
  'sort_by' => 'Sắp xếp theo',
  'relevance' => 'Độ liên quan',
  'date' => 'Ngày',
  'popularity' => 'Độ phổ biến',
  'search_criteria' => 'Tiêu chí tìm kiếm',
  'unknown' => 'Không xác định',
  'any' => 'Bất kỳ',
  'present' => 'Hiện tại',
  'modify_search' => 'Chỉnh sửa tìm kiếm',
  'descending' => 'Giảm dần',
  'ascending' => 'Tăng dần',
  'actions.advanced_desc' => 'Tìm kiếm chi tiết với nhiều tiêu chí',
  'form.submit' => 'Tìm kiếm',
);
