<?php

return [
    'profile' => 'Profile',
    'settings' => 'Settings',
    'account' => 'Account',
    'preferences' => 'Preferences',
    'privacy' => 'Privacy',
    'security' => 'Security',
    'notifications' => 'Notifications',
    'avatar' => 'Avatar',
    'cover_photo' => 'Cover Photo',
    'bio' => 'Bio',
    'location' => 'Location',
    'website' => 'Website',
    'social_links' => 'Social Links',
    'joined_date' => 'Joined Date',
    'last_seen' => 'Last Seen',
    'posts_count' => 'Posts Count',
    'threads_count' => 'Threads Count',
    'reputation' => 'Reputation',
    'badges' => 'Badges',
    'achievements' => 'Achievements',
    'followers' => 'Followers',
    'following' => 'Following',
    'friends' => 'Friends',
    'blocked_users' => 'Blocked Users',
    'email_notifications' => 'Email Notifications',
    'push_notifications' => 'Push Notifications',
    'language' => 'Language',
    'timezone' => 'Timezone',
    'theme' => 'Theme',
    'password' => 'Password',
    'two_factor' => 'Two Factor Authentication',
    'login_history' => 'Login History',
    'active_sessions' => 'Active Sessions',
    'delete_account' => 'Delete Account',
    'export_data' => 'Export Data',
    'members' => 'Members',
    'online' => 'Online',
    'offline' => 'Offline',
    'status' => 'Status',
    'role' => 'Role',
    'permissions' => 'Permissions',
];
