<?php

/**
 * Vietnamese translations for user/profile
 * Profile localization - Updated: 2025-07-20 03:38:15
 * Total keys: 55
 */

return [
    'account' => 'Tài khoản',
    'achievements' => 'Thành tích',
    'actions' => [
        'cancel_order' => 'Hủy đơn',
        'search' => 'Tìm kiếm',
    ],
    'active_sessions' => 'Phiên hoạt động',
    'avatar' => 'Ảnh đại diện',
    'badges' => 'Huy hiệu',
    'bio' => 'Tiểu sử',
    'blocked_users' => 'Người dùng bị chặn',
    'cover_photo' => 'Ảnh bìa',
    'delete_account' => 'Xóa tài khoản',
    'email_notifications' => 'Thông báo email',
    'export_data' => 'Xuất dữ liệu',
    'followers' => 'Người theo dõi',
    'following' => 'Đang theo dõi',
    'friends' => 'Bạn bè',
    'joined_date' => 'Ngày tham gia',
    'labels' => [
        'activity' => 'Hoạt động',
        'all_roles' => 'Tất cả vai trò',
        'favorites' => 'Yêu thích',
        'history' => 'Lịch sử',
        'notifications' => 'Thông báo',
        'orders' => 'Đơn hàng',
        'password' => 'Mật khẩu',
        'personal_info' => 'Thông tin cá nhân',
        'reviews' => 'Đánh giá',
        'role' => 'Vai trò',
        'security' => 'Bảo mật',
        'settings' => 'Cài đặt',
    ],
    'language' => 'Ngôn ngữ',
    'last_seen' => 'Lần cuối trực tuyến',
    'location' => 'Vị trí',
    'login_history' => 'Lịch sử đăng nhập',
    'members' => 'Thành viên',
    'notifications' => 'Thông báo',
    'offline' => 'Ngoại tuyến',
    'online' => 'Trực tuyến',
    'password' => 'Mật khẩu',
    'permissions' => 'Quyền hạn',
    'posts_count' => 'Số bài viết',
    'preferences' => 'Tùy chọn',
    'privacy' => 'Riêng tư',
    'profile' => 'Hồ sơ',
    'push_notifications' => 'Thông báo đẩy',
    'reputation' => 'Danh tiếng',
    'role' => 'Vai trò',
    'security' => 'Bảo mật',
    'settings' => 'Cài đặt',
    'social_links' => 'Liên kết mạng xã hội',
    'status' => [
        'cancelled' => 'Đã hủy',
    ],
    'theme' => 'Giao diện',
    'threads_count' => 'Số chủ đề',
    'timezone' => 'Múi giờ',
    'two_factor' => 'Xác thực hai yếu tố',
    'website' => 'Website',
];
