@extends('layouts.app-full')

@section('title', $documentation->meta_title ?: $documentation->title)
@section('meta_description', $documentation->meta_description ?: $documentation->excerpt)

@push('styles')
<link rel="stylesheet" href="{{ asset_versioned('css/frontend/page/tool.css') }}">
@endpush

@section('content')
<div class="body_page">
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="mb-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('tools.documentation') }}">Documentation</a></li>
            @if($documentation->category)
                <li class="breadcrumb-item">
                    <span>{{ $documentation->category->name }}</span>
                </li>
            @endif
            <li class="breadcrumb-item active" aria-current="page">{{ $documentation->title }}</li>
        </ol>
    </nav>

    <div class="row">
        <!-- Main Content -->
        <div class="col-lg-9">
            <!-- Document Header -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start mb-3">
                        <div>
                            <span class="badge bg-{{ $documentation->content_type === 'api' ? 'success' : 'primary' }} mb-2">
                                {{ ucfirst($documentation->content_type) }}
                            </span>
                            <span class="badge bg-secondary mb-2 ms-1">
                                {{ ucfirst($documentation->difficulty_level) }}
                            </span>
                            @if(!$documentation->is_public)
                                <span class="badge bg-warning mb-2 ms-1">
                                    <i class="fas fa-lock"></i> Private
                                </span>
                            @endif
                        </div>
                        <div class="text-end">
                            <small class="text-muted">
                                <i class="fas fa-eye"></i> {{ number_format($documentation->view_count) }} views
                            </small>
                        </div>
                    </div>

                    <h1 class="h2 mb-3">{{ $documentation->title }}</h1>

                    @if($documentation->excerpt)
                        <p class="lead text-muted mb-3">{{ $documentation->excerpt }}</p>
                    @endif

                    <div class="documentation-content">
                        {!! \Illuminate\Support\Str::markdown($documentation->content) !!}
                    </div>
                    <h6 class="card-title">Tags</h6>
                    @foreach($documentation->tags as $tag)
                        <span class="badge bg-light text-dark me-1 mb-1">{{ $tag }}</span>
                    @endforeach
                </div>
            </div>
        </div>

        <!-- Sidebar -->
        <div class="col-lg-3">
            <!-- Table of Contents -->
            <div class="card mb-4">
                <div class="card-header">
                    <h6 class="mb-0"><i class="fas fa-list"></i> Table of Contents</h6>
                </div>
                <div class="card-body">
                    <div id="toc">
                        <!-- TOC will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Related Documents -->
            @if($relatedDocs && $relatedDocs->count() > 0)
                <div class="card mb-4">
                    <div class="card-header">
                        <h6 class="mb-0"><i class="fas fa-link"></i> Related Documents</h6>
                    </div>
                    <div class="card-body">
                        @foreach($relatedDocs as $related)
                            <div class="mb-3">
                                <a href="{{ route('tools.documentation.show', $related) }}" class="text-decoration-none">
                                    <h6 class="mb-1">{{ $related->title }}</h6>
                                </a>
                                <p class="small text-muted mb-1">{{ Str::limit($related->excerpt, 80) }}</p>
                                <small class="text-muted">
                                    <i class="fas fa-eye"></i> {{ number_format($related->view_count) }} views
                                </small>
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif

            <!-- Quick Actions -->
            <div class="card">
                <div class="card-header">
                    <h6 class="mb-0"><i class="fas fa-tools"></i> Quick Actions</h6>
                </div>
                <div class="card-body">
                    <div class="d-grid gap-2">
                        <a href="{{ route('tools.documentation') }}" class="btn btn-outline-primary btn-sm">
                            <i class="fas fa-arrow-left"></i> Back to Documentation
                        </a>
                        @if($documentation->category)
                            <a href="{{ route('tools.documentation', ['category' => $documentation->category->id]) }}"
                               class="btn btn-outline-secondary btn-sm">
                                <i class="fas fa-folder"></i> View Category
                            </a>
                        @endif
                        <button class="btn btn-outline-info btn-sm" onclick="window.print()">
                            <i class="fas fa-print"></i> Print Document
                        </button>
                        <button class="btn btn-outline-success btn-sm" onclick="copyToClipboard()">
                            <i class="fas fa-copy"></i> Copy URL
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
// Generate Table of Contents
document.addEventListener('DOMContentLoaded', function() {
    const content = document.querySelector('.documentation-content');
    const toc = document.getElementById('toc');
    const headings = content.querySelectorAll('h1, h2, h3, h4, h5, h6');

    if (headings.length > 0) {
        const tocList = document.createElement('ul');
        tocList.className = 'list-unstyled';

        headings.forEach((heading, index) => {
            const id = 'heading-' + index;
            heading.id = id;

            const li = document.createElement('li');
            li.className = 'mb-1';

            const link = document.createElement('a');
            link.href = '#' + id;
            link.textContent = heading.textContent;
            link.className = 'text-decoration-none small';

            // Add indentation based on heading level
            const level = parseInt(heading.tagName.charAt(1));
            if (level > 1) {
                link.style.paddingLeft = (level - 1) * 15 + 'px';
            }

            li.appendChild(link);
            tocList.appendChild(li);
        });

        toc.appendChild(tocList);
    } else {
        toc.innerHTML = '<p class="text-muted small">No headings found</p>';
    }
});

// Copy URL to clipboard
function copyToClipboard() {
    navigator.clipboard.writeText(window.location.href).then(function() {
        alert('URL copied to clipboard!');
    });
}

// Rating functionality (temporarily disabled - will be implemented later)
@auth
document.querySelectorAll('.rating-stars i').forEach(star => {
    star.addEventListener('click', function() {
        alert('Rating functionality will be implemented soon!');
        // TODO: Implement rating API endpoint
    });
});

// Comment form (temporarily disabled - will be implemented later)
document.getElementById('comment-form').addEventListener('submit', function(e) {
    e.preventDefault();
    alert('Comment functionality will be implemented soon!');
    // TODO: Implement comment API endpoint
});
@endauth
</script>
@endpush
