<?php

/**
 * Vietnamese translations for features/forum
 * Forum discussions and threads
 * 
 * Structure: features.forum.*
 * Populated: 2025-07-20 02:37:52
 * Keys: 156
 */

return [
    'threads' => [
        'create' => 'Tạo thảo luận',
        'edit' => 'Chỉnh sửa thảo luận',
        'delete' => 'Xóa thảo luận',
        'sticky' => 'Ghim',
        'locked' => 'Khóa',
    ],
    'posts' => [
        'reply' => 'Trả lời',
        'quote' => 'Trích dẫn',
        'edit' => 'Chỉnh sửa',
        'delete' => 'Xóa',
    ],
    'replies' => 'Phản hồi',
    'views' => 'Lượt xem',
    'latest_post' => 'Bài viết mới nhất',
    'create_thread' => 'Tạo chủ đề',
    'reply' => 'Trả lời',
    'edit' => 'Chỉnh sửa',
    'delete' => 'Xóa',
    'pin' => 'Ghim',
    'lock' => 'Khóa',
    'categories' => [
        'all' => 'Tất cả danh mục',
        'select' => 'Chọn danh mục',
    ],
    'forums' => 'Diễn đàn',
    'discussions' => 'Thảo luận',
    'participants' => 'Người tham gia',
    'moderators' => 'Người điều hành',
    'rules' => 'Quy tắc',
    'guidelines' => 'Hướng dẫn',
    'search_forums' => 'Tìm kiếm diễn đàn',
    'no_threads' => 'Chưa có chủ đề nào',
    'no_posts' => 'Chưa có bài viết nào',
    'thread_locked' => 'Chủ đề đã bị khóa',
    'thread_pinned' => 'Chủ đề đã được ghim',
    'last_activity' => 'Hoạt động cuối',
    'created_by' => 'Được tạo bởi',
    'started_by' => 'Bắt đầu bởi',
    'follow' => 'Theo dõi',
    'following' => 'Đang theo dõi',
    'go_to_end' => 'Đến cuối',
    'actions' => [
        'new_thread' => 'Tạo chủ đề mới',
        'create_thread' => 'Tạo chủ đề',
        'create_first_thread' => 'Tạo chủ đề đầu tiên',
        'reply' => 'Trả lời',
        'edit' => 'Chỉnh sửa',
        'delete' => 'Xóa',
        'pin' => 'Ghim',
        'lock' => 'Khóa',
        'view_more' => 'Xem thêm',
        'view_all' => 'Xem tất cả',
        'clear_filters' => 'Xóa bộ lọc',
        'search' => 'Tìm kiếm',
        'sort' => 'Sắp xếp',
        'filter' => 'Lọc',
    ],
    'status' => [
        'sticky' => 'Ghim',
        'locked' => 'Khóa',
        'solved' => 'Đã giải quyết',
        'closed' => 'Đã đóng',
        'archived' => 'Đã lưu trữ',
        'featured' => 'Nổi bật',
        'hot' => 'Hot',
        'new' => 'Mới',
    ],
    'create' => [
        'title' => 'Tạo Chủ Đề Mới',
        'subtitle' => 'Chia sẻ ý tưởng, thảo luận và kết nối với cộng đồng',
        'back' => 'Quay Lại',
        'progress_label' => 'Tiến độ tạo chủ đề',
        'step_basic' => 'Thông Tin Cơ Bản',
        'step_content' => 'Nội Dung',
        'step_poll' => 'Khảo Sát (Tùy Chọn)',
        'step_review' => 'Xem Lại',
        'step_basic_aria' => 'Bước 1: Thông tin cơ bản',
        'step_content_aria' => 'Bước 2: Nội dung',
        'step_poll_aria' => 'Bước 3: Khảo sát tùy chọn',
        'step_review_aria' => 'Bước 4: Xem lại và hoàn tất',
        'previous' => 'Trước',
        'create_button' => 'Tạo Chủ Đề',
        'content_placeholder' => 'Viết nội dung chi tiết cho chủ đề của bạn...',
    ],
    'search' => [
        'placeholder' => 'Tìm kiếm chủ đề trong diễn đàn này...',
        'placeholder_main' => 'Tìm kiếm diễn đàn, chủ đề và thảo luận...',
        'description' => 'Tìm kiếm trên tất cả diễn đàn và thảo luận. Tối thiểu 3 ký tự.',
        'no_results' => 'Không tìm thấy kết quả',
        'results_for' => 'Kết quả cho',
        'results' => 'Kết quả tìm kiếm',
    ],
    'poll' => [
        'closed' => 'Đã đóng',
        'closes' => 'Đóng',
        'closes_at' => 'Đóng :time',
        'vote' => 'Bình chọn',
        'view_results' => 'Xem kết quả',
        'total_votes' => 'Tổng số phiếu bầu',
        'change_vote' => 'Thay đổi phiếu bầu',
        'update_vote' => 'Cập nhật phiếu bầu',
        'cancel' => 'Hủy',
        'loading' => 'Đang tải...',
        'loading_results' => 'Đang tải kết quả...',
        'voters' => 'Người bình chọn',
        'vote_limit_message' => 'Bạn chỉ có thể chọn tối đa :max tùy chọn.',
        'max_options_exceeded' => 'Bạn chỉ có thể chọn tối đa :max tùy chọn.',
        'votes' => '{0} phiếu|{1} phiếu|[2,*] phiếu',
        'vote_singular' => 'phiếu bầu',
    ],
    'metadata' => [
        'views_count' => 'Lượt xem',
        'replies_count' => 'Phản hồi',
        'participants_count' => 'Người tham gia',
        'last_post_by' => 'Bài viết cuối bởi',
        'posts_count' => 'Bài viết',
        'comments_count' => 'Bình luận',
        'joined' => 'Tham gia',
    ],
    'sort' => [
        'latest_activity' => 'Hoạt động mới nhất',
        'oldest_first' => 'Cũ nhất trước',
        'most_replies' => 'Nhiều phản hồi nhất',
        'most_views' => 'Nhiều lượt xem nhất',
        'newest_first' => 'Mới nhất trước',
        'alphabetical' => 'Theo bảng chữ cái',
    ],
    'filter' => [
        'all' => 'Tất cả',
        'recent' => 'Gần đây',
        'unanswered' => 'Chưa trả lời',
        'solved' => 'Đã giải quyết',
        'unsolved' => 'Chưa giải quyết',
        'pinned' => 'Đã ghim',
        'locked' => 'Đã khóa',
    ],
    'stats' => [
        'forums' => 'Diễn đàn',
        'threads' => 'Bài đăng',
        'views' => 'Lượt xem',
        'comments' => 'Bình luận',
        'posts' => 'Bài viết',
        'members' => 'Thành viên',
        'online' => 'Trực tuyến',
    ],
    'category' => [
        'forums_in_category' => 'Diễn đàn trong danh mục này',
        'forums_in' => 'Diễn đàn trong :category',
        'recent_threads' => ':count bài đăng mới nhất',
        'recent_posts' => ':count bài đăng gần đây',
        'no_threads' => 'Chưa có bài đăng nào trong danh mục này',
        'no_forums' => 'Chưa có diễn đàn nào trong danh mục này',
        'view_category' => 'Xem danh mục',
        'category_stats' => 'Thống kê danh mục',
    ],
    'description' => 'Thảo luận các chủ đề kỹ thuật cơ khí với cộng đồng',
    'newest_member' => 'Thành viên mới nhất',
    'title' => 'Diễn đàn',
    'forum' => [
        'no_forums' => 'Chưa có diễn đàn nào',
        'forum_stats' => 'Thống kê diễn đàn',
        'recent_activity' => 'Hoạt động gần đây',
        'moderators' => 'Người điều hành',
        'rules' => 'Quy tắc',
        'guidelines' => 'Hướng dẫn',
    ],
    'time' => [
        'last_post' => 'Bài viết cuối',
        'last_activity' => 'Hoạt động cuối',
        'created_at' => 'Được tạo lúc',
        'updated_at' => 'Cập nhật lúc',
        'posted_by' => 'Đăng bởi',
        'started_by' => 'Bắt đầu bởi',
        'replied_by' => 'Trả lời bởi',
    ],
    'messages' => [
        'thread_created' => 'Chủ đề đã được tạo thành công',
        'thread_updated' => 'Chủ đề đã được cập nhật',
        'thread_deleted' => 'Chủ đề đã được xóa',
        'post_created' => 'Bài viết đã được tạo',
        'post_updated' => 'Bài viết đã được cập nhật',
        'post_deleted' => 'Bài viết đã được xóa',
        'access_denied' => 'Bạn không có quyền truy cập',
        'login_required' => 'Vui lòng đăng nhập để tiếp tục',
    ],
    'permissions' => [
        'view_forum' => 'Xem diễn đàn',
        'create_thread' => 'Tạo chủ đề',
        'reply_thread' => 'Trả lời chủ đề',
        'edit_post' => 'Chỉnh sửa bài viết',
        'delete_post' => 'Xóa bài viết',
        'moderate' => 'Điều hành',
    ],
    'sidebar' => [
        'technical_discussions' => 'Thảo luận Kỹ thuật',
        'engineers' => 'Kỹ sư',
        'weekly_activity' => 'Hoạt động Tuần',
        'growth_rate' => 'Tỷ lệ Tăng trưởng',
        'weekly_trends' => 'Xu hướng Tuần',
        'featured_discussions' => 'Thảo luận Nổi bật',
        'top_engineers' => 'Kỹ sư Hàng đầu',
        'active_forums' => 'Diễn đàn Hoạt động',
        'view_all' => 'Xem tất cả',
        'leaderboard' => 'Bảng xếp hạng',
        'low_activity' => 'Hoạt động Thấp',
        'new_this_month' => 'mới trong tháng',
        'points' => 'điểm',
        'discussions' => 'thảo luận',
        'recently' => 'gần đây',
        'join_professional_network' => 'Tham gia Mạng lưới Chuyên nghiệp',
    ],
    'navigation' => [
        'home' => 'Trang chủ',
        'forums' => 'Diễn đàn',
        'categories' => 'Danh mục',
        'threads' => 'Chủ đề',
        'search' => 'Tìm kiếm',
        'latest' => 'Mới nhất',
        'popular' => 'Phổ biến',
        'trending' => 'Xu hướng',
    ],
    'unfollow' => 'Bỏ theo dõi',
    'bookmark' => 'Lưu',
    'bookmarked' => 'Đã lưu',
    'like' => 'Thích',
    'liked' => 'Đã thích',
    'share' => 'Chia sẻ',
    'quote' => 'Trích dẫn',
    'pinned' => 'Đã ghim',
    'locked' => 'Đã khóa',
    'featured' => 'Nổi bật',
    'closed' => 'Đã đóng',
    'last_post' => 'Bài viết cuối',
    'last_post_by' => 'Bài viết cuối bởi',
    'created_at' => 'Tạo lúc',
    'updated_at' => 'Cập nhật lúc',
    'comments' => 'bình luận',
    'joined' => 'Tham gia',
    'image_gallery' => 'Album ảnh',
    'image_gallery_count' => 'Album ảnh (:count)',
    'no_comments' => 'Chưa có bình luận nào. Hãy là người đầu tiên bình luận!',
    'post_reply' => 'Đăng phản hồi',
    'reply_content' => 'Nội dung phản hồi',
    'reply_content_placeholder' => 'Nhập nội dung phản hồi của bạn...',
    'reply_content_required' => 'Vui lòng nhập nội dung phản hồi',
    'sending' => 'Đang gửi...',
    'send_reply' => 'Gửi phản hồi',
    'sort_oldest' => 'Cũ nhất',
    'sort_newest' => 'Mới nhất',
    'sort_reactions' => 'Nhiều tương tác',
    'copy_link' => 'Sao chép liên kết',
    'link_copied' => 'Đã sao chép liên kết!',
    'delete_confirmation' => 'Xác nhận xóa',
    'delete_thread_message' => 'Bạn có chắc chắn muốn xóa chủ đề này? Hành động này không thể hoàn tác.',
    'delete_comment_message' => 'Bạn có chắc chắn muốn xóa bình luận này?',
    'delete_reply_message' => 'Bạn có chắc chắn muốn xóa phản hồi này?',
    'delete_thread_button' => 'Xóa chủ đề',
    'cancel' => 'Hủy',
    'form_submission_error' => 'Có lỗi xảy ra khi gửi phản hồi. Vui lòng thử lại.',
    'follow_success' => 'Đã theo dõi thread thành công',
    'unfollow_success' => 'Đã bỏ theo dõi thread thành công',
    'follow_error' => 'Có lỗi khi theo dõi thread',
    'unfollow_error' => 'Có lỗi khi bỏ theo dõi thread',
    'login_required' => 'Vui lòng :login hoặc :register để đăng phản hồi.',
    'login' => 'đăng nhập',
    'register' => 'đăng ký',
];
