<?php

/**
 * Vietnamese translations for features/showcase
 * Project showcases and portfolios
 * 
 * Structure: features.showcase.*
 * Populated: 2025-07-20 02:37:52
 * Keys: 26
 */

return [
    'public_showcases' => 'Dự án công khai',
    'page_description' => 'Khám phá các dự án cơ khí, sản phẩm kỹ thuật, và giải pháp công nghệ từ cộng đồng.',
    'create_new' => 'Tạo Showcase Mới',
    'create_new_project' => 'Tạo dự án mới',
    'featured_projects' => 'Dự án nổi bật',
    'project_categories' => 'Danh mục dự án',
    'advanced_search' => 'Tìm kiếm nâng cao',
    'all_projects' => 'Tất cả dự án',
    'project_name' => 'Tên dự án',
    'category' => 'Danh mục',
    'complexity' => 'Độ phức tạp',
    'project_type' => 'Loại dự án',
    'software' => 'Phần mềm',
    'min_rating' => 'Đánh giá tối thiểu',
    'sort_by' => 'Sắp xếp',
    'search_placeholder' => 'Nhập tên hoặc mô tả dự án...',
    'all_categories' => 'Tất cả danh mục',
    'all_levels' => 'Tất cả mức độ',
    'all_types' => 'Tất cả loại',
    'all_software' => 'Tất cả phần mềm',
    'all_ratings' => 'Tất cả đánh giá',
    '4_plus_stars' => '4+ sao',
    '3_plus_stars' => '3+ sao',
    '2_plus_stars' => '2+ sao',
    'newest' => 'Mới nhất',
    'oldest' => 'Cũ nhất',
    'most_viewed' => 'Xem nhiều nhất',
    'highest_rated' => 'Đánh giá cao nhất',
    'most_downloads' => 'Tải nhiều nhất',
    'search' => 'Tìm kiếm',
    'searching' => 'Đang tìm kiếm',
    'clear_filters' => 'Xóa bộ lọc',
    'projects' => [
        'create' => 'Tạo dự án',
        'edit' => 'Chỉnh sửa dự án',
        'view' => 'Xem dự án',
        'featured' => 'Dự án nổi bật',
    ],
    'avg_rating' => 'Đánh giá TB',
    'results' => 'kết quả',
    'ratings' => 'đánh giá',
    'no_featured_projects' => 'Chưa có dự án nổi bật nào.',
    'no_projects_found' => 'Không tìm thấy dự án nào',
    'try_different_filters' => 'Thử thay đổi bộ lọc tìm kiếm hoặc tạo dự án mới.',
    'complexity_levels' => [
        'beginner' => 'Người mới',
        'intermediate' => 'Trung bình',
        'advanced' => 'Nâng cao',
        'expert' => 'Chuyên gia',
    ],
    'view_category_showcases' => 'Xem tất cả dự án :category',
    'project_showcase' => 'Dự Án Showcase',
    'discover_engineering_projects' => 'Khám phá các dự án kỹ thuật cơ khí',
    'total_projects' => 'Tổng dự án',
    'downloads' => 'Lượt tải',
    'total_views' => 'Lượt xem',
    'create_project' => 'Tạo dự án',
    'popular_categories' => 'Danh mục phổ biến',
    'popular_software' => 'Phần mềm phổ biến',
    'top_contributors' => 'Người đóng góp hàng đầu',
    'views' => 'lượt xem',
    'features' => [
        'cad' => 'CAD',
        'download' => 'Tải xuống',
        'simulation' => 'Mô phỏng',
        'analysis' => 'Phân tích',
    ],
    'categories' => [
        'web' => 'Web Development',
        'mobile' => 'Mobile Apps',
        'design' => 'Design',
    ],
    'beginner' => 'Người mới',
    'intermediate' => 'Trung bình',
    'advanced' => 'Nâng cao',
    'expert' => 'Chuyên gia',
    'design' => 'Thiết kế',
    'manufacturing' => 'Sản xuất',
    'analysis' => 'Phân tích',
    'design_type' => 'Thiết kế',
    'manufacturing_type' => 'Sản xuất',
    'new' => 'Showcase mới',
    'related' => 'Showcase liên quan',
    'for_thread' => 'Showcase cho chủ đề',
    'create_from_thread' => 'Tạo Showcase từ Thread này',
    'create_from_thread_description' => 'Chuyển đổi thread thành showcase để highlight dự án của bạn',
    'create_showcase_info' => 'Showcase sẽ giúp dự án của bạn được nhiều người biết đến hơn và có thể nhận được đánh giá từ cộng đồng.',
    'create_showcase_button' => 'Tạo Showcase',
    'create_from_thread_title' => 'Tạo Showcase từ Thread',
    'basic_info' => 'Thông tin cơ bản',
    'content' => 'Nội dung',
    'complete' => 'Hoàn tất',
    'step_1_title' => 'Bước 1: Thông tin cơ bản',
    'step_2_title' => 'Bước 2: Nội dung Showcase',
    'step_3_title' => 'Bước 3: Xác nhận tạo Showcase',
    'showcase_title' => 'Tiêu đề Showcase',
    'showcase_title_help' => 'Tiêu đề sẽ được sử dụng làm tên showcase',
    'select_category' => 'Chọn danh mục',
    'select_project_type' => 'Chọn loại dự án',
    'project_description' => 'Mô tả dự án',
    'project_description_help' => 'Mô tả chi tiết về dự án, phương pháp và kết quả đạt được',
    'cover_image' => 'Ảnh đại diện',
    'cover_image_help' => 'Chọn ảnh đại diện cho showcase (JPG, PNG, GIF, WebP - tối đa 5MB)',
    'current_thread_image' => 'Ảnh hiện tại từ thread:',
    'complexity_level' => 'Mức độ phức tạp',
    'industry_application' => 'Ứng dụng ngành',
    'industry_placeholder' => 'VD: Automotive, Aerospace, Manufacturing',
    'confirm_info' => 'Xác nhận thông tin:',
    'confirm_points' => [
        'Showcase sẽ được tạo từ nội dung thread hiện tại',
        'Thread gốc vẫn được giữ nguyên',
        'Showcase có thể được chỉnh sửa sau khi tạo',
        'Cộng đồng có thể đánh giá và bình luận về showcase',
    ],
    'agree_terms' => 'Tôi đồng ý cho phép cộng đồng xem và đánh giá showcase này',
    'previous' => 'Trước',
    'next' => 'Tiếp theo',
    'create_showcase' => 'Tạo Showcase',
    'creating' => 'Đang tạo...',
    'file_attachments' => 'File đính kèm',
    'file_attachments_optional' => 'Tùy chọn',
    'file_upload_area' => 'Kéo thả file vào đây hoặc',
    'browse_files' => 'chọn file',
    'file_upload_help' => 'Hỗ trợ: Images (JPG, PNG, GIF, WebP), Documents (PDF, DOC, DOCX), CAD Files (DWG, DXF, STEP, STL)',
    'file_upload_limits' => 'Tối đa 10 file, mỗi file không quá 50MB',
    'file_upload_description' => 'Thêm file CAD, hình ảnh, tài liệu kỹ thuật để minh họa cho dự án của bạn',
    'files_selected' => 'File đã chọn:',
    'file_too_large' => 'File \":filename\" quá lớn. Kích thước tối đa là 50MB.',
    'file_type_not_supported' => 'File \":filename\" không được hỗ trợ.',
    'max_files_exceeded' => 'Chỉ được chọn tối đa 10 file',
    'file_validation_failed' => 'Vui lòng kiểm tra lại các file đã chọn',
    'file_types' => [
        'image' => 'Hình ảnh',
        'document' => 'Tài liệu',
        'cad' => 'File CAD',
        'spreadsheet' => 'Bảng tính',
        'presentation' => 'Thuyết trình',
        'archive' => 'File nén',
        'other' => 'Khác',
    ],
    'title_required' => 'Vui lòng nhập tiêu đề showcase',
    'category_required' => 'Vui lòng chọn danh mục',
    'description_required' => 'Vui lòng nhập mô tả dự án',
    'cover_image_required' => 'Vui lòng chọn ảnh đại diện',
    'file_size_error' => 'Kích thước file không được vượt quá 5MB',
    'terms_required' => 'Vui lòng đồng ý với điều khoản',
];
