<?php

/**
 * English translations for features/forum
 * Forum discussions and threads
 * 
 * Structure: features.forum.*
 * Populated: 2025-07-20 02:37:52
 * Keys: 156
 */

return [
    'threads' => [
        'create' => 'Create Thread',
        'edit' => 'Edit Thread',
        'delete' => 'Delete Thread',
        'sticky' => 'Sticky',
        'locked' => 'Locked',
    ],
    'posts' => [
        'reply' => 'Reply',
        'quote' => 'Quote',
        'edit' => 'Edit',
        'delete' => 'Delete',
    ],
    'replies' => 'Replies',
    'views' => 'Views',
    'latest_post' => 'Latest Post',
    'create_thread' => 'Create Thread',
    'reply' => 'Reply',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'pin' => 'Pin',
    'lock' => 'Lock',
    'categories' => [
        'all' => 'All Categories',
        'select' => 'Select Category',
    ],
    'forums' => 'Forums',
    'discussions' => 'Discussions',
    'participants' => 'Participants',
    'moderators' => 'Moderators',
    'rules' => 'Rules',
    'guidelines' => 'Guidelines',
    'search_forums' => 'Search Forums',
    'no_threads' => 'No threads yet',
    'no_posts' => 'No posts yet',
    'thread_locked' => 'Thread is locked',
    'thread_pinned' => 'Thread is pinned',
    'last_activity' => 'Last Activity',
    'created_by' => 'Created by',
    'started_by' => 'Started by',
    'follow' => 'Follow',
    'following' => 'Following',
    'go_to_end' => 'Go to end',
    'actions' => [
        'new_thread' => 'New Thread',
        'create_thread' => 'Create Thread',
        'create_first_thread' => 'Create First Thread',
        'reply' => 'Reply',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'pin' => 'Pin',
        'lock' => 'Lock',
        'view_more' => 'View More',
        'view_all' => 'View All',
        'clear_filters' => 'Clear Filters',
        'search' => 'Search',
        'sort' => 'Sort',
        'filter' => 'Filter',
    ],
    'status' => [
        'sticky' => 'Sticky',
        'locked' => 'Locked',
        'solved' => 'Solved',
        'closed' => 'Closed',
        'archived' => 'Archived',
        'featured' => 'Featured',
        'hot' => 'Hot',
        'new' => 'New',
    ],
    'create' => [
        'title' => 'Create New Thread',
        'subtitle' => 'Share ideas, discuss and connect with the community',
        'back' => 'Back',
        'progress_label' => 'Thread creation progress',
        'step_basic' => 'Basic Information',
        'step_content' => 'Content',
        'step_poll' => 'Poll (Optional)',
        'step_review' => 'Review',
        'step_basic_aria' => 'Step 1: Basic information',
        'step_content_aria' => 'Step 2: Content',
        'step_poll_aria' => 'Step 3: Optional poll',
        'step_review_aria' => 'Step 4: Review and complete',
        'previous' => 'Previous',
        'create_button' => 'Create Thread',
        'content_placeholder' => 'Write detailed content for your thread...',
    ],
    'search' => [
        'placeholder' => 'Search threads in this forum...',
        'placeholder_main' => 'Search forums, threads, and discussions...',
        'description' => 'Search across all forums and discussions. Minimum 3 characters required.',
        'no_results' => 'No results found',
        'results_for' => 'Results for',
        'results' => 'Search Results',
    ],
    'poll' => [
        'closed' => 'Closed',
        'closes' => 'Closes',
        'closes_at' => 'Closes :time',
        'vote' => 'Vote',
        'view_results' => 'View Results',
        'total_votes' => 'Total votes',
        'change_vote' => 'Change Vote',
        'update_vote' => 'Update Vote',
        'cancel' => 'Cancel',
        'loading' => 'Loading...',
        'loading_results' => 'Loading results...',
        'voters' => 'Voters',
        'vote_limit_message' => 'You can only select up to :max options.',
        'max_options_exceeded' => 'You can only select up to :max options.',
        'votes' => '{0} votes|{1} vote|[2,*] votes',
        'vote_singular' => 'vote',
    ],
    'metadata' => [
        'views_count' => 'Views',
        'replies_count' => 'Replies',
        'participants_count' => 'Participants',
        'last_post_by' => 'Last post by',
        'posts_count' => 'Posts',
        'comments_count' => 'Comments',
        'joined' => 'Joined',
    ],
    'sort' => [
        'latest_activity' => 'Latest Activity',
        'oldest_first' => 'Oldest First',
        'most_replies' => 'Most Replies',
        'most_views' => 'Most Views',
        'newest_first' => 'Newest First',
        'alphabetical' => 'Alphabetical',
    ],
    'filter' => [
        'all' => 'All',
        'recent' => 'Recent',
        'unanswered' => 'Unanswered',
        'solved' => 'Solved',
        'unsolved' => 'Unsolved',
        'pinned' => 'Pinned',
        'locked' => 'Locked',
    ],
    'stats' => [
        'forums' => 'Forums',
        'threads' => 'Threads',
        'views' => 'Views',
        'comments' => 'Comments',
        'posts' => 'Posts',
        'members' => 'Members',
        'online' => 'Online',
    ],
    'category' => [
        'forums_in_category' => 'Forums in this category',
        'forums_in' => 'Forums in :category',
        'recent_threads' => ':count recent posts',
        'recent_posts' => ':count recent posts',
        'no_threads' => 'No posts in this category yet',
        'no_forums' => 'No forums in this category yet',
        'view_category' => 'View Category',
        'category_stats' => 'Category Statistics',
    ],
    'description' => 'Discuss mechanical engineering topics with the community',
    'newest_member' => 'Newest Member',
    'title' => 'Forums',
    'forum' => [
        'no_forums' => 'No forums yet',
        'forum_stats' => 'Forum Statistics',
        'recent_activity' => 'Recent Activity',
        'moderators' => 'Moderators',
        'rules' => 'Rules',
        'guidelines' => 'Guidelines',
    ],
    'time' => [
        'last_post' => 'Last Post',
        'last_activity' => 'Last Activity',
        'created_at' => 'Created at',
        'updated_at' => 'Updated at',
        'posted_by' => 'Posted by',
        'started_by' => 'Started by',
        'replied_by' => 'Replied by',
    ],
    'messages' => [
        'thread_created' => 'Thread created successfully',
        'thread_updated' => 'Thread updated successfully',
        'thread_deleted' => 'Thread deleted successfully',
        'post_created' => 'Post created successfully',
        'post_updated' => 'Post updated successfully',
        'post_deleted' => 'Post deleted successfully',
        'access_denied' => 'Access denied',
        'login_required' => 'Please login to continue',
    ],
    'permissions' => [
        'view_forum' => 'View Forum',
        'create_thread' => 'Create Thread',
        'reply_thread' => 'Reply to Thread',
        'edit_post' => 'Edit Post',
        'delete_post' => 'Delete Post',
        'moderate' => 'Moderate',
    ],
    'sidebar' => [
        'technical_discussions' => 'Technical Discussions',
        'engineers' => 'Engineers',
        'weekly_activity' => 'Weekly Activity',
        'growth_rate' => 'Growth Rate',
        'weekly_trends' => 'Weekly Trends',
        'featured_discussions' => 'Featured Discussions',
        'top_engineers' => 'Top Engineers',
        'active_forums' => 'Active Forums',
        'view_all' => 'View All',
        'leaderboard' => 'Leaderboard',
        'low_activity' => 'Low Activity',
        'new_this_month' => 'new this month',
        'points' => 'points',
        'discussions' => 'discussions',
        'recently' => 'recently',
        'join_professional_network' => 'Join Professional Network',
    ],
    'navigation' => [
        'home' => 'Home',
        'forums' => 'Forums',
        'categories' => 'Categories',
        'threads' => 'Threads',
        'search' => 'Search',
        'latest' => 'Latest',
        'popular' => 'Popular',
        'trending' => 'Trending',
    ],
    'unfollow' => 'Unfollow',
    'bookmark' => 'Bookmark',
    'bookmarked' => 'Bookmarked',
    'like' => 'Like',
    'liked' => 'Liked',
    'share' => 'Share',
    'quote' => 'Quote',
    'pinned' => 'Pinned',
    'locked' => 'Locked',
    'featured' => 'Featured',
    'closed' => 'Closed',
    'comments' => 'Comments',
    'joined' => 'Joined',
    'last_post' => 'Last post',
    'last_post_by' => 'Last post by',
    'created_at' => 'Created at',
    'updated_at' => 'Updated at',
    'sort_oldest' => 'Oldest',
    'sort_newest' => 'Newest',
    'sort_reactions' => 'Most Reactions',
    'post_reply' => 'Post Reply',
    'reply_content' => 'Reply Content',
    'send_reply' => 'Send Reply',
    'image_gallery' => 'Image Gallery',
    'image_gallery_count' => 'Image Gallery (:count)',
    'no_comments' => 'No comments yet. Be the first to comment!',
    'reply_content_placeholder' => 'Enter your reply content...',
    'reply_content_required' => 'Please enter reply content',
    'sending' => 'Sending...',
    'copy_link' => 'Copy Link',
    'link_copied' => 'Link copied!',
    'delete_confirmation' => 'Confirm Delete',
    'delete_thread_message' => 'Are you sure you want to delete this thread? This action cannot be undone.',
    'delete_comment_message' => 'Are you sure you want to delete this comment?',
    'delete_reply_message' => 'Are you sure you want to delete this reply?',
    'delete_thread_button' => 'Delete Thread',
    'cancel' => 'Cancel',
    'form_submission_error' => 'An error occurred while submitting the reply. Please try again.',
    'follow_success' => 'Successfully followed thread',
    'unfollow_success' => 'Successfully unfollowed thread',
    'follow_error' => 'Error following thread',
    'unfollow_error' => 'Error unfollowing thread',
    'login_required' => 'Please :login or :register to post a reply.',
    'login' => 'login',
    'register' => 'register',
];
