<?php

/**
 * English translations for features/showcase
 * Enhanced migration with source integration
 * 
 * Structure: features.showcase.*
 * Enhanced: 2025-07-20 02:51:02
 * Source keys found: 114
 * Total keys: 22
 */

return [
    'public_showcases' => 'Public Showcases',
    'page_description' => 'Explore mechanical projects, technical products, and technology solutions from the community.',
    'create_new' => 'Create New Showcase',
    'create_new_project' => 'Create new project',
    'featured_projects' => 'Featured Projects',
    'project_categories' => 'Project Categories',
    'advanced_search' => 'Advanced Search',
    'all_projects' => 'All Projects',
    'project_name' => 'Project Name',
    'category' => 'Category',
    'complexity' => 'Complexity',
    'project_type' => 'Project Type',
    'software' => 'Software',
    'min_rating' => 'Minimum Rating',
    'sort_by' => 'Sort by',
    'search_placeholder' => 'Enter project name or description...',
    'all_categories' => 'All Categories',
    'all_levels' => 'All Levels',
    'all_types' => 'All Types',
    'all_software' => 'All Software',
    'all_ratings' => 'All Ratings',
    '4_plus_stars' => '4+ stars',
    '3_plus_stars' => '3+ stars',
    '2_plus_stars' => '2+ stars',
    'newest' => 'Newest',
    'oldest' => 'Oldest',
    'most_viewed' => 'Most Viewed',
    'highest_rated' => 'Highest Rated',
    'most_downloads' => 'Most Downloads',
    'search' => 'Search',
    'searching' => 'Searching',
    'clear_filters' => 'Clear Filters',
    'projects' => 'projects',
    'avg_rating' => 'Avg Rating',
    'results' => 'results',
    'ratings' => 'ratings',
    'no_featured_projects' => 'No featured projects yet.',
    'no_projects_found' => 'No projects found',
    'try_different_filters' => 'Try changing search filters or create a new project.',
    'complexity_levels' => [
        'beginner' => 'Beginner',
        'intermediate' => 'Intermediate',
        'advanced' => 'Advanced',
        'expert' => 'Expert',
    ],
    'view_category_showcases' => 'View all :category projects',
    'features' => [
        'cad' => 'CAD',
        'download' => 'Download',
        'simulation' => 'Simulation',
        'analysis' => 'Analysis',
    ],
    'categories' => [
        'design' => 'Design',
        'manufacturing' => 'Manufacturing',
        'analysis' => 'Analysis',
    ],
    'project_showcase' => 'Project Showcase',
    'discover_engineering_projects' => 'Discover engineering projects',
    'total_projects' => 'Total Projects',
    'downloads' => 'Downloads',
    'total_views' => 'Total Views',
    'create_project' => 'Create Project',
    'popular_categories' => 'Popular Categories',
    'popular_software' => 'Popular Software',
    'top_contributors' => 'Top Contributors',
    'views' => 'views',
    'beginner' => 'Beginner',
    'intermediate' => 'Intermediate',
    'advanced' => 'Advanced',
    'expert' => 'Expert',
    'design' => 'Design',
    'manufacturing' => 'Manufacturing',
    'analysis' => 'Analysis',
    'design_type' => 'Design',
    'manufacturing_type' => 'Manufacturing',
    'new' => 'New Showcases',
    'related' => 'Related Showcases',
    'for_thread' => 'Showcase for Thread',
    'create_from_thread' => 'Create Showcase from this Thread',
    'create_from_thread_description' => 'Convert thread to showcase to highlight your project',
    'create_showcase_info' => 'Showcase will help your project get more visibility and receive feedback from the community.',
    'create_showcase_button' => 'Create Showcase',
    'create_from_thread_title' => 'Create Showcase from Thread',
    'basic_info' => 'Basic Information',
    'content' => 'Content',
    'complete' => 'Complete',
    'step_1_title' => 'Step 1: Basic Information',
    'step_2_title' => 'Step 2: Showcase Content',
    'step_3_title' => 'Step 3: Confirm Creation',
    'showcase_title' => 'Showcase Title',
    'showcase_title_help' => 'Title will be used as showcase name',
    'select_category' => 'Select category',
    'select_project_type' => 'Select project type',
    'project_description' => 'Project Description',
    'project_description_help' => 'Detailed description of project, methods and results achieved',
    'cover_image' => 'Cover Image',
    'cover_image_help' => 'Select cover image for showcase (JPG, PNG, GIF, WebP - max 5MB)',
    'current_thread_image' => 'Current image from thread:',
    'complexity_level' => 'Complexity Level',
    'industry_application' => 'Industry Application',
    'industry_placeholder' => 'e.g.: Automotive, Aerospace, Manufacturing',
    'file_attachments' => 'File Attachments',
    'file_attachments_optional' => 'Optional',
    'file_upload_area' => 'Drag and drop files here or',
    'browse_files' => 'browse files',
    'file_upload_help' => 'Supported: Images (JPG, PNG, GIF, WebP), Documents (PDF, DOC, DOCX), CAD Files (DWG, DXF, STEP, STL)',
    'file_upload_limits' => 'Maximum 10 files, each file no more than 50MB',
    'file_upload_description' => 'Add CAD files, images, technical documents to illustrate your project',
    'files_selected' => 'Selected files:',
    'file_too_large' => 'File \":filename\" is too large. Maximum size is 50MB.',
    'file_type_not_supported' => 'File \":filename\" is not supported.',
    'max_files_exceeded' => 'Maximum 10 files allowed',
    'file_validation_failed' => 'Please check the selected files',
    'file_types' => [
        'image' => 'Image',
        'document' => 'Document',
        'cad' => 'CAD File',
        'spreadsheet' => 'Spreadsheet',
        'presentation' => 'Presentation',
        'archive' => 'Archive',
        'other' => 'Other',
    ],
    'confirm_info' => 'Confirm information:',
    'confirm_points' => [
        'Showcase will be created from current thread content',
        'Original thread will remain unchanged',
        'Showcase can be edited after creation',
        'Community can rate and comment on showcase',
    ],
    'agree_terms' => 'I agree to allow community to view and rate this showcase',
    'previous' => 'Previous',
    'next' => 'Next',
    'create_showcase' => 'Create Showcase',
    'creating' => 'Creating...',
    'title_required' => 'Please enter showcase title',
    'category_required' => 'Please select category',
    'description_required' => 'Please enter project description',
    'cover_image_required' => 'Please select cover image',
    'file_size_error' => 'File size cannot exceed 5MB',
    'terms_required' => 'Please agree to the terms',
];
