<?php

/**
 * Vietnamese translations for content/home
 * Enhanced migration with source integration
 * 
 * Structure: content.home.*
 * Enhanced: 2025-07-20 02:51:02
 * Source keys found: 64
 * Total keys: 0
 */

return [
    'hero_title' => 'Cộng đồng Kỹ thuật Cơ khí',
    'hero_highlight' => 'Hàng đầu Việt Nam',
    'hero_subtitle' => 'Nơi hội tụ 10,000+ kỹ sư, chia sẻ kiến thức và phát triển sự nghiệp trong lĩnh vực cơ khí',
    'engineers' => 'Kỹ sư',
    'discussions' => 'Thảo luận',
    'companies' => 'Công ty',
    'join_free' => 'Tham gia miễn phí',
    'explore_community' => 'Khám phá cộng đồng',
    'join_discussion' => 'Tham gia thảo luận',
    'explore_marketplace' => 'Khám phá thị trường',
    'why_choose_mechamap' => 'Tại sao chọn MechaMap?',
    'value_proposition_subtitle' => 'Nền tảng toàn diện cho cộng đồng kỹ thuật cơ khí Việt Nam',
    'learn_value' => 'Học hỏi',
    'learn_description' => 'Tiếp cận kiến thức từ chuyên gia hàng đầu và tài liệu kỹ thuật chất lượng cao',
    'connect_value' => 'Kết nối',
    'connect_description' => 'Networking với 10,000+ kỹ sư chuyên nghiệp và xây dựng mạng lưới quan hệ',
    'opportunity_value' => 'Cơ hội',
    'opportunity_description' => 'Tìm việc làm, dự án freelance và cơ hội phát triển sự nghiệp',
    'practice_value' => 'Thực hành',
    'practice_description' => 'Chia sẻ dự án, nhận feedback và cải thiện kỹ năng thực tế',
    'quick_actions' => 'Thao tác nhanh',
    'quick_actions_subtitle' => 'Bắt đầu hành trình của bạn với MechaMap',
    'quick_search' => 'Tìm kiếm nhanh',
    'quick_search_desc' => 'Tìm câu trả lời cho vấn đề kỹ thuật trong vòng vài giây',
    'ask_question' => 'Đặt câu hỏi',
    'ask_question_desc' => 'Nhận hỗ trợ từ chuyên gia trong vòng 24 giờ',
    'learn_resources' => 'Tài liệu học tập',
    'learn_resources_desc' => 'Truy cập thư viện tài liệu kỹ thuật phong phú',
    'find_jobs' => 'Tìm việc làm',
    'find_jobs_desc' => 'Khám phá cơ hội việc làm mới trong ngành cơ khí',
    'latest_discussions' => 'Thảo luận mới nhất',
    'no_discussions' => 'Chưa có thảo luận nào',
    'live_activity' => 'Hoạt động trực tiếp',
    'top_contributors' => 'Người đóng góp hàng đầu',
    'points' => 'điểm',
    'no_contributors' => 'Chưa có dữ liệu người đóng góp',
    'weekly_challenge' => 'Thử thách tuần',
    'current_challenge' => 'Thiết kế hệ thống truyền động',
    'challenge_description' => 'Tham gia thử thách thiết kế và thể hiện kỹ năng của bạn',
    'completed' => 'hoàn thành',
    'trusted_by' => 'Được tin tưởng bởi',
    'trusted_subtitle' => 'Hàng nghìn kỹ sư và doanh nghiệp đã tin tưởng MechaMap',
    'testimonial_1' => 'MechaMap đã giúp tôi kết nối với nhiều chuyên gia và tìm được công việc mơ ước. Cộng đồng rất hữu ích và thân thiện.',
    'testimonial_2' => 'Tài liệu kỹ thuật trên MechaMap rất chất lượng. Tôi đã học được nhiều kiến thức mới và áp dụng vào công việc.',
    'testimonial_3' => 'Là một nhà quản lý, tôi thường tìm kiếm nhân tài trên MechaMap. Đây là nơi tập trung những kỹ sư giỏi nhất.',
    'senior_engineer' => 'Kỹ sư cao cấp',
    'cad_specialist' => 'Chuyên gia CAD',
    'manufacturing_manager' => 'Quản lý sản xuất',
    'stay_updated' => 'Luôn cập nhật thông tin mới nhất',
    'newsletter_description' => 'Đăng ký nhận tin để không bỏ lỡ những thông tin và cơ hội quan trọng',
    'enter_email' => 'Nhập địa chỉ email của bạn',
    'search_now' => 'Tìm kiếm ngay',
    'ask_now' => 'Đặt câu hỏi ngay',
    'explore_now' => 'Khám phá ngay',
    'find_now' => 'Tìm kiếm ngay',
    'join_challenge' => 'Tham gia thử thách',
    'subscribe' => 'Đăng ký',
    'view_all' => 'Xem tất cả',
    'created_new_thread' => 'đã tạo chủ đề mới',
    'provided_helpful_answer' => 'đã đưa ra câu trả lời hữu ích',
    'joined_community' => 'đã tham gia cộng đồng',
    'newsletter_success' => 'Cảm ơn bạn đã đăng ký nhận tin!',
    'featured_showcases' => 'Dự án nổi bật',
    'featured_showcases_desc' => 'Khám phá những dự án cơ khí ấn tượng từ cộng đồng',
];
