<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

// Load Laravel application
$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo "🔧 Adding Simple Manufacturing Processes Data...\n";

// Simple manufacturing processes data
$processes = [
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'CNC Milling',
        'code' => 'CNC-MILL-001',
        'description' => 'Computer Numerical Control milling process for precision machining of complex parts with high accuracy and repeatability.',
        'category' => 'Machining',
        'subcategory' => 'CNC Machining',
        'process_type' => 'Subtractive',
        'materials_compatible' => json_encode(['Steel', 'Aluminum', 'Titanium', 'Plastic']),
        'typical_applications' => json_encode(['Aerospace components', 'Automotive parts', 'Medical devices', 'Precision tooling']),
        'required_equipment' => json_encode(['CNC Milling Machine', 'Cutting tools', 'Workholding fixtures', 'CAM software']),
        'setup_cost' => 150.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 5,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => true,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'CNC Turning',
        'code' => 'CNC-TURN-001',
        'description' => 'Precision turning process using computer-controlled lathes for cylindrical parts with excellent dimensional accuracy.',
        'category' => 'Machining',
        'subcategory' => 'CNC Machining',
        'process_type' => 'Subtractive',
        'materials_compatible' => json_encode(['Steel', 'Aluminum', 'Brass', 'Stainless Steel']),
        'typical_applications' => json_encode(['Shafts and rods', 'Bushings and sleeves', 'Threaded components', 'Precision pins']),
        'required_equipment' => json_encode(['CNC Lathe', 'Turning tools', 'Chuck and tailstock', 'Measuring instruments']),
        'setup_cost' => 120.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 3,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => true,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => '3D Printing (FDM)',
        'code' => '3DP-FDM-001',
        'description' => 'Fused Deposition Modeling additive manufacturing process for rapid prototyping and low-volume production.',
        'category' => 'Additive Manufacturing',
        'subcategory' => '3D Printing',
        'process_type' => 'Additive',
        'materials_compatible' => json_encode(['PLA', 'ABS', 'PETG', 'TPU']),
        'typical_applications' => json_encode(['Prototypes and models', 'Custom fixtures', 'Educational models', 'Low-stress components']),
        'required_equipment' => json_encode(['3D Printer (FDM)', 'Filament materials', 'Slicing software', 'Post-processing tools']),
        'setup_cost' => 50.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 2,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => true,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Sheet Metal Forming',
        'code' => 'SMF-001',
        'description' => 'Metal forming process using press brakes and forming tools to create bent and shaped sheet metal components.',
        'category' => 'Forming',
        'subcategory' => 'Sheet Metal',
        'process_type' => 'Forming',
        'materials_compatible' => json_encode(['Steel', 'Aluminum', 'Stainless Steel', 'Copper']),
        'typical_applications' => json_encode(['Enclosures and housings', 'Brackets and supports', 'Automotive body panels', 'HVAC components']),
        'required_equipment' => json_encode(['Press Brake', 'Forming dies', 'Sheet metal shears', 'Measuring tools']),
        'setup_cost' => 100.00,
        'minimum_quantity' => 10,
        'lead_time_days' => 3,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => false,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Laser Cutting',
        'code' => 'LC-001',
        'description' => 'High-precision cutting process using focused laser beam for clean cuts in various materials with minimal heat-affected zone.',
        'category' => 'Cutting',
        'subcategory' => 'Laser Processing',
        'process_type' => 'Cutting',
        'materials_compatible' => json_encode(['Steel', 'Aluminum', 'Stainless Steel', 'Acrylic']),
        'typical_applications' => json_encode(['Sheet metal fabrication', 'Signage and displays', 'Automotive components', 'Electronics enclosures']),
        'required_equipment' => json_encode(['Laser cutting machine', 'Assist gas system', 'Material handling', 'Fume extraction']),
        'setup_cost' => 200.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 2,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => false,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Injection Molding',
        'code' => 'IM-001',
        'description' => 'High-volume plastic manufacturing process using heated plastic injected into precision molds for consistent parts.',
        'category' => 'Molding',
        'subcategory' => 'Plastic Molding',
        'process_type' => 'Molding',
        'materials_compatible' => json_encode(['ABS', 'Polypropylene', 'Nylon', 'Polycarbonate']),
        'typical_applications' => json_encode(['Consumer products', 'Automotive components', 'Electronic housings', 'Medical devices']),
        'required_equipment' => json_encode(['Injection molding machine', 'Precision molds', 'Material handling', 'Quality control equipment']),
        'setup_cost' => 5000.00,
        'minimum_quantity' => 1000,
        'lead_time_days' => 42,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => true,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'TIG Welding',
        'code' => 'TIG-001',
        'description' => 'Tungsten Inert Gas welding process for high-quality joints in various metals with excellent control and precision.',
        'category' => 'Joining',
        'subcategory' => 'Welding',
        'process_type' => 'Joining',
        'materials_compatible' => json_encode(['Steel', 'Stainless Steel', 'Aluminum', 'Titanium']),
        'typical_applications' => json_encode(['Aerospace structures', 'Pressure vessels', 'Food processing equipment', 'Architectural metalwork']),
        'required_equipment' => json_encode(['TIG welding machine', 'Tungsten electrodes', 'Shielding gas', 'Safety equipment']),
        'setup_cost' => 80.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 5,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => false,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Surface Grinding',
        'code' => 'SG-001',
        'description' => 'Precision surface finishing process using abrasive wheels to achieve tight tolerances and excellent surface quality.',
        'category' => 'Finishing',
        'subcategory' => 'Grinding',
        'process_type' => 'Finishing',
        'materials_compatible' => json_encode(['Steel', 'Stainless Steel', 'Tool Steel', 'Ceramics']),
        'typical_applications' => json_encode(['Precision tooling', 'Bearing surfaces', 'Gauge blocks', 'Machine components']),
        'required_equipment' => json_encode(['Grinding machine', 'Grinding wheels', 'Coolant system', 'Precision measuring tools']),
        'setup_cost' => 120.00,
        'minimum_quantity' => 1,
        'lead_time_days' => 4,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => false,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Electroplating',
        'code' => 'EP-001',
        'description' => 'Electrochemical process for applying thin metal coatings to improve corrosion resistance, appearance, and functionality.',
        'category' => 'Surface Treatment',
        'subcategory' => 'Coating',
        'process_type' => 'Surface Treatment',
        'materials_compatible' => json_encode(['Steel', 'Copper', 'Aluminum', 'Plastic (conductive)']),
        'typical_applications' => json_encode(['Decorative finishes', 'Corrosion protection', 'Electronic components', 'Automotive trim']),
        'required_equipment' => json_encode(['Electroplating tanks', 'Power supplies', 'Chemical handling', 'Waste treatment system']),
        'setup_cost' => 300.00,
        'minimum_quantity' => 10,
        'lead_time_days' => 5,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => false,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'uuid' => \Illuminate\Support\Str::uuid(),
        'name' => 'Investment Casting',
        'code' => 'IC-001',
        'description' => 'Precision casting process using wax patterns and ceramic molds for complex, near-net-shape components.',
        'category' => 'Casting',
        'subcategory' => 'Precision Casting',
        'process_type' => 'Casting',
        'materials_compatible' => json_encode(['Steel', 'Stainless Steel', 'Titanium', 'Superalloys']),
        'typical_applications' => json_encode(['Aerospace components', 'Gas turbine parts', 'Medical implants', 'Jewelry and art']),
        'required_equipment' => json_encode(['Wax injection equipment', 'Ceramic shell system', 'Furnaces', 'Finishing equipment']),
        'setup_cost' => 2000.00,
        'minimum_quantity' => 50,
        'lead_time_days' => 28,
        'status' => 'approved',
        'is_active' => true,
        'is_featured' => true,
        'usage_count' => 0,
        'view_count' => 0,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
];

try {
    // Clear existing data
    DB::table('manufacturing_processes')->truncate();
    echo "🗑️ Cleared existing manufacturing processes data.\n";

    // Insert new data
    foreach ($processes as $process) {
        DB::table('manufacturing_processes')->insert($process);
        echo "✅ Added: {$process['name']}\n";
    }

    echo "\n🎉 Successfully added " . count($processes) . " manufacturing processes!\n";
    echo "📊 Categories: Machining, Additive Manufacturing, Forming, Cutting, Molding, Joining, Finishing, Surface Treatment, Casting\n";

} catch (Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
    exit(1);
}

echo "\n✅ Manufacturing Processes Database populated successfully!\n";
