<?php

/**
 * Vietnamese translations for ui/buttons
 * Enhanced migration with source integration
 * 
 * Structure: ui.buttons.*
 * Enhanced: 2025-07-20 02:51:02
 * Source keys found: 109
 * Total keys: 0
 */

return [
    'save' => 'Lưu',
    'submit' => 'Gửi',
    'send' => 'Gửi',
    'create' => 'Tạo',
    'add' => 'Thêm',
    'update' => 'Cập nhật',
    'edit' => 'Chỉnh sửa',
    'delete' => 'Xóa',
    'remove' => 'Loại bỏ',
    'cancel' => 'Hủy',
    'close' => 'Đóng',
    'back' => 'Quay lại',
    'next' => 'Tiếp theo',
    'previous' => 'Trước',
    'continue' => 'Tiếp tục',
    'finish' => 'Hoàn thành',
    'done' => 'Xong',
    'ok' => 'OK',
    'yes' => 'Có',
    'no' => 'Không',
    'confirm' => 'Xác nhận',
    'apply' => 'Áp dụng',
    'reset' => 'Đặt lại',
    'clear' => 'Xóa',
    'refresh' => 'Làm mới',
    'reload' => 'Tải lại',
    'dashboard' => 'Bảng điều khiển',
    'profile' => 'Hồ sơ',
    'settings' => 'Cài đặt',
    'logout' => 'Đăng xuất',
    'register' => 'Đăng ký',
    'sign_in' => 'Đăng nhập',
    'sign_up' => 'Đăng ký',
    'sign_out' => 'Đăng xuất',
    'view' => 'Xem',
    'view_all' => 'Xem tất cả',
    'view_more' => 'Xem thêm',
    'show' => 'Hiển thị',
    'hide' => 'Ẩn',
    'expand' => 'Mở rộng',
    'collapse' => 'Thu gọn',
    'toggle' => 'Chuyển đổi',
    'select' => 'Chọn',
    'deselect' => 'Bỏ chọn',
    'select_all' => 'Chọn tất cả',
    'deselect_all' => 'Bỏ chọn tất cả',
    'check_all' => 'Đánh dấu tất cả',
    'uncheck_all' => 'Bỏ đánh dấu tất cả',
    'upload' => 'Tải lên',
    'download' => 'Tải xuống',
    'import' => 'Nhập',
    'export' => 'Xuất',
    'browse' => 'Duyệt',
    'choose_file' => 'Chọn tệp',
    'attach' => 'Đính kèm',
    'detach' => 'Tháo',
    'filter' => 'Lọc',
    'sort' => 'Sắp xếp',
    'sort_asc' => 'Sắp xếp tăng dần',
    'sort_desc' => 'Sắp xếp giảm dần',
    'clear_filters' => 'Xóa bộ lọc',
    'advanced_search' => 'Tìm kiếm nâng cao',
    'reply' => 'Trả lời',
    'comment' => 'Bình luận',
    'share' => 'Chia sẻ',
    'like' => 'Thích',
    'unlike' => 'Bỏ thích',
    'follow' => 'Theo dõi',
    'unfollow' => 'Bỏ theo dõi',
    'subscribe' => 'Đăng ký',
    'unsubscribe' => 'Hủy đăng ký',
    'bookmark' => 'Đánh dấu',
    'unbookmark' => 'Bỏ đánh dấu',
    'report' => 'Báo cáo',
    'block' => 'Chặn',
    'unblock' => 'Bỏ chặn',
    'publish' => 'Xuất bản',
    'unpublish' => 'Hủy xuất bản',
    'draft' => 'Bản nháp',
    'archive' => 'Lưu trữ',
    'unarchive' => 'Bỏ lưu trữ',
    'activate' => 'Kích hoạt',
    'deactivate' => 'Vô hiệu hóa',
    'enable' => 'Bật',
    'disable' => 'Tắt',
    'approve' => 'Phê duyệt',
    'reject' => 'Từ chối',
    'pending' => 'Chờ xử lý',
    'buy_now' => 'Mua ngay',
    'add_to_cart' => 'Thêm vào giỏ',
    'checkout' => 'Thanh toán',
    'pay' => 'Thanh toán',
    'order' => 'Đặt hàng',
    'quote' => 'Báo giá',
    'contact_seller' => 'Liên hệ người bán',
    'compare' => 'So sánh',
    'wishlist' => 'Danh sách yêu thích',
    'help' => 'Trợ giúp',
    'support' => 'Hỗ trợ',
    'contact' => 'Liên hệ',
    'feedback' => 'Phản hồi',
    'report_issue' => 'Báo cáo sự cố',
    'tutorial' => 'Hướng dẫn',
    'documentation' => 'Tài liệu',
    'faq' => 'Câu hỏi thường gặp',
    'view_details' => 'Xem chi tiết',
    'home' => 'Trang chủ',
    'login' => 'Đăng nhập',
    'search' => 'Tìm kiếm',
];
