<?php

/**
 * Vietnamese translations for content/pages
 * Static pages and general content
 * 
 * Structure: content.pages.*
 * Populated: 2025-07-20 02:35:44
 * Keys: 53
 */

return [
    'about' => [
        'title' => 'Giới thiệu',
        'description' => 'Về MechaMap và cộng đồng',
    ],
    'contact' => [
        'title' => 'Liên hệ',
        'email' => 'Email liên hệ',
        'phone' => 'Số điện thoại',
    ],
    'terms' => [
        'title' => 'Điều khoản sử dụng',
        'acceptance' => 'Chấp nhận điều khoản',
    ],
    'privacy' => [
        'title' => 'Chính sách bảo mật',
        'last_updated' => 'Cập nhật lần cuối',
    ],
    'rules' => [
        'title' => 'Quy tắc cộng đồng',
        'description' => 'Quy tắc và hướng dẫn tham gia cộng đồng',
        'general_rules' => 'Quy tắc chung',
        'posting_guidelines' => 'Hướng dẫn đăng bài',
        'consequences' => 'Hậu quả vi phạm',
    ],
    'help' => [
        'title' => 'Trợ giúp',
        'description' => 'Trung tâm trợ giúp và hướng dẫn',
        'faq' => 'Câu hỏi thường gặp',
        'tutorials' => 'Hướng dẫn sử dụng',
        'support' => 'Hỗ trợ kỹ thuật',
    ],
    'faq' => [
        'title' => 'Câu hỏi thường gặp',
        'description' => 'Các câu hỏi và câu trả lời phổ biến',
        'question' => 'Câu hỏi',
        'answer' => 'Câu trả lời',
    ],
    'errors' => [
        [
            'title' => 'Không tìm thấy trang',
            'message' => 'Trang bạn đang tìm kiếm không tồn tại.',
            'back_home' => 'Về trang chủ',
        ],
        [
            'title' => 'Truy cập bị từ chối',
            'message' => 'Bạn không có quyền truy cập trang này.',
        ],
        [
            'title' => 'Lỗi máy chủ',
            'message' => 'Đã xảy ra lỗi máy chủ. Vui lòng thử lại sau.',
        ],
    ],
    'knowledge' => [
        'title' => 'Cơ sở tri thức',
        'description' => 'Kho tài liệu và kiến thức kỹ thuật',
        'categories' => 'Danh mục',
        'articles' => 'Bài viết',
        'search_placeholder' => 'Tìm kiếm bài viết...',
        'no_results' => 'Không tìm thấy kết quả nào.',
    ],
    'technical' => [
        'title' => 'Tài nguyên kỹ thuật',
        'description' => 'Tài liệu và công cụ kỹ thuật',
        'materials' => 'Vật liệu',
        'standards' => 'Tiêu chuẩn',
        'cad_library' => 'Thư viện CAD',
        'processes' => 'Quy trình sản xuất',
    ],
    'community' => [
        'title' => 'Cộng đồng',
        'description' => 'Kết nối với cộng đồng kỹ sư',
        'members' => 'Thành viên',
        'events' => 'Sự kiện',
        'companies' => 'Công ty',
        'jobs' => 'Việc làm',
        'leaderboard' => 'Bảng xếp hạng',
        'online_members' => 'Thành viên trực tuyến',
    ],
    'all_content' => 'Tất cả nội dung',
    'search_in_thread' => 'Tìm trong chủ đề',
    'search_in_forum' => 'Tìm trong diễn đàn',
    'advanced_search' => 'Tìm kiếm nâng cao',
    'active_since' => 'Hoạt động từ',
    'join_community' => 'Tham gia cộng đồng',
    'business_development' => 'Phát triển kinh doanh',
    'latest_updates' => 'Cập nhật mới nhất',
    'trending_topics' => 'Chủ đề thịnh hành',
    'featured_content' => 'Nội dung nổi bật',
    'popular_posts' => 'Bài viết phổ biến',
    'recent_activity' => 'Hoạt động gần đây',
    'community_stats' => 'Thống kê cộng đồng',
    'online_members' => 'Thành viên trực tuyến',
    'total_posts' => 'Tổng số bài viết',
    'total_threads' => 'Tổng số chủ đề',
    'new_members' => 'Thành viên mới',
    'categories' => 'Danh mục',
    'tags' => 'Thẻ',
    'filters' => 'Bộ lọc',
    'sort_by' => 'Sắp xếp theo',
    'date_created' => 'Ngày tạo',
    'last_updated' => 'Cập nhật cuối',
    'most_viewed' => 'Xem nhiều nhất',
    'most_liked' => 'Thích nhiều nhất',
    'most_replied' => 'Trả lời nhiều nhất',
    'load_more' => 'Tải thêm',
    'show_more' => 'Hiển thị thêm',
    'show_less' => 'Hiển thị ít hơn',
    'read_more' => 'Đọc thêm',
    'read_less' => 'Thu gọn',
    'share' => 'Chia sẻ',
    'bookmark' => 'Đánh dấu',
    'report' => 'Báo cáo',
    'subscribe' => 'Đăng ký',
    'unsubscribe' => 'Hủy đăng ký',
    'follow' => 'Theo dõi',
    'unfollow' => 'Hủy theo dõi',
    'like' => 'Thích',
    'unlike' => 'Bỏ thích',
    'comment' => 'Bình luận',
    'reply' => 'Trả lời',
    'quote' => 'Trích dẫn',
    'edit' => 'Chỉnh sửa',
    'delete' => 'Xóa',
    'restore' => 'Khôi phục',
    'archive' => 'Lưu trữ',
    'pin' => 'Ghim',
    'unpin' => 'Bỏ ghim',
    'lock' => 'Khóa',
    'unlock' => 'Mở khóa',
    'approve' => 'Phê duyệt',
    'reject' => 'Từ chối',
    'pending' => 'Đang chờ',
    'published' => 'Đã xuất bản',
    'draft' => 'Bản nháp',
    'private' => 'Riêng tư',
    'public' => 'Công khai',
    'featured' => 'Nổi bật',
    'sticky' => 'Dính',
    'closed' => 'Đã đóng',
    'open' => 'Mở',
    'solved' => 'Đã giải quyết',
    'unsolved' => 'Chưa giải quyết',
    'verified' => 'Đã xác minh',
    'unverified' => 'Chưa xác minh',
    'or' => 'hoặc',
    'and' => 'và',
    'processing' => 'Đang xử lý...',
    'error_occurred' => 'Có lỗi xảy ra. Vui lòng thử lại.',
    'new_message' => 'Tin nhắn mới',
    'minimize' => 'Thu gọn',
    'list' => 'Danh sách',
    'chat' => 'Chat',
    'showcase_item' => 'Mục trưng bày',
    'welcome' => 'Chào mừng',
    'logged_in_message' => 'Bạn đã đăng nhập thành công!',
    'knowledge_hub' => 'Nơi hội tụ tri thức cơ khí',
    'connect_engineers' => 'Kết nối với 64+ kỹ sư chuyên nghiệp',
    'join_discussions' => 'Tham gia 118+ thảo luận kỹ thuật',
    'share_experience' => 'Chia sẻ kinh nghiệm CAD/CAM/CNC',
    'join_engineering_community' => 'Tham gia cộng đồng kỹ thuật cơ khí hàng đầu',
    'featured_topics' => 'Chủ đề nổi bật',
    'no_featured_topics' => 'Chưa có chủ đề nổi bật',
    'view_more' => 'Xem thêm',
    'view_all' => 'Xem tất cả',
    'popular_forums' => 'Diễn đàn phổ biến',
    'no_forums' => 'Chưa có diễn đàn nào',
    'active_members' => 'Thành viên tích cực',
    'contributions' => 'đóng góp',
    'no_active_members' => 'Chưa có thành viên tích cực',
    'related_communities' => 'Cộng đồng liên quan',
    'topics' => 'chủ đề',
    'topic' => 'chủ đề',
    'mechamap_community' => 'Cộng đồng MechaMap',
    'professional_network' => 'Mạng lưới Kỹ sư Chuyên nghiệp',
    'technical_discussions' => 'Thảo luận Kỹ thuật',
    'engineers' => 'Kỹ sư',
    'weekly_activity' => 'Hoạt động tuần này',
    'growth_rate' => 'Tỷ lệ tăng trưởng',
    'join_professional_network' => 'Tham gia Mạng lưới Chuyên nghiệp',
    'weekly_trends' => 'Xu hướng tuần này',
    'points' => 'điểm',
    'discussions' => 'thảo luận',
    'featured_discussions' => 'Thảo luận Nổi bật',
    'in' => 'trong',
    'top_engineers' => 'Thành viên hàng đầu',
    'leaderboard' => 'Bảng xếp hạng',
    'recently' => 'gần đây',
    'recommendations_for_you' => 'Đề xuất cho bạn',
    'by' => 'bởi',
    'active_forums' => 'Diễn đàn Hoạt động',
    'new_this_month' => 'mới trong tháng',
    'high_activity' => 'Hoạt động Cao',
    'medium_activity' => 'Hoạt động Trung bình',
    'low_activity' => 'Hoạt động Thấp',
    'page_title' => 'Sắp Ra Mắt',
    'title' => 'Sắp Ra Mắt',
    'default_feature' => 'Tính Năng Mới',
    'default_description' => 'Chúng tôi đang phát triển tính năng mới thú vị để mang lại trải nghiệm tốt nhất cho cộng đồng kỹ sư cơ khí.',
    'default_timeline' => 'Q2 2025',
    'timeline_title' => 'Thời Gian Dự Kiến',
    'progress_label' => 'Tiến Độ Phát Triển',
    'notify_title' => 'Nhận thông báo khi ra mắt',
    'email_placeholder' => 'Nhập email của bạn',
    'notify_button' => 'Đăng ký thông báo',
    'notify_description' => 'Chúng tôi sẽ gửi email thông báo khi tính năng này sẵn sàng.',
    'notify_success' => 'Đã đăng ký!',
    'back_button' => 'Quay lại',
    'explore_forums' => 'Khám phá diễn đàn',
    'share_excitement' => 'Chia sẻ sự hào hứng của bạn:',
    'copy_link' => 'Sao chép link',
    'copied' => 'Đã sao chép!',
    'share_text' => 'Tính năng mới thú vị sắp ra mắt trên MechaMap! 🚀',
];
