<?php

/**
 * English translations for content/pages
 * Enhanced migration with source integration
 * 
 * Structure: content.pages.*
 * Enhanced: 2025-07-20 02:51:02
 * Source keys found: 127
 * Total keys: 63
 */

return [
    'about' => [
        'title' => 'About',
        'description' => 'Learn about MechaMap',
        'content' => 'About page content',
    ],
    'contact' => [
        'title' => 'Contact',
        'description' => 'Get in touch with us',
        'name' => 'Name',
        'email' => 'Email',
        'subject' => 'Subject',
        'message' => 'Message',
        'send' => 'Send Message',
        'success' => 'Message sent successfully!',
    ],
    'terms' => [
        'title' => 'Terms of Service',
        'description' => 'Terms and conditions of service',
        'last_updated' => 'Last updated',
    ],
    'privacy' => [
        'title' => 'Privacy Policy',
        'description' => 'User information privacy policy',
        'data_collection' => 'Data Collection',
        'data_usage' => 'Data Usage',
        'data_protection' => 'Data Protection',
    ],
    'rules' => [
        'title' => 'Community Rules',
        'description' => 'Community rules and guidelines',
        'general_rules' => 'General Rules',
        'posting_guidelines' => 'Posting Guidelines',
        'consequences' => 'Violation Consequences',
    ],
    'help' => [
        'title' => 'Help',
        'description' => 'Help center and guides',
        'faq' => 'Frequently Asked Questions',
        'tutorials' => 'Tutorials',
        'support' => 'Technical Support',
    ],
    'faq' => [
        'title' => 'Frequently Asked Questions',
        'description' => 'Common questions and answers',
        'question' => 'Question',
        'answer' => 'Answer',
    ],
    'errors' => [
        [
            'title' => 'Page Not Found',
            'message' => 'The page you are looking for does not exist.',
            'back_home' => 'Back to Home',
        ],
        [
            'title' => 'Access Denied',
            'message' => 'You do not have permission to access this page.',
        ],
        [
            'title' => 'Server Error',
            'message' => 'A server error occurred. Please try again later.',
        ],
    ],
    'knowledge' => [
        'title' => 'Knowledge Base',
        'description' => 'Technical documentation and knowledge repository',
        'categories' => 'Categories',
        'articles' => 'Articles',
        'search_placeholder' => 'Search articles...',
        'no_results' => 'No results found.',
    ],
    'technical' => [
        'title' => 'Technical Resources',
        'description' => 'Technical documentation and tools',
        'materials' => 'Materials',
        'standards' => 'Standards',
        'cad_library' => 'CAD Library',
        'processes' => 'Manufacturing Processes',
    ],
    'community' => [
        'title' => 'Community',
        'description' => 'Connect with the engineering community',
        'members' => 'Members',
        'events' => 'Events',
        'companies' => 'Companies',
        'jobs' => 'Jobs',
        'leaderboard' => 'Leaderboard',
        'online_members' => 'Online Members',
    ],
    'all_content' => 'All Content',
    'search_in_thread' => 'Search in Thread',
    'search_in_forum' => 'Search in Forum',
    'advanced_search' => 'Advanced Search',
    'active_since' => 'Active Since',
    'join_community' => 'Join Community',
    'business_development' => 'Business Development',
    'latest_updates' => 'Latest Updates',
    'trending_topics' => 'Trending Topics',
    'featured_content' => 'Featured Content',
    'popular_posts' => 'Popular Posts',
    'recent_activity' => 'Recent Activity',
    'community_stats' => 'Community Stats',
    'online_members' => 'Online Members',
    'total_posts' => 'Total Posts',
    'total_threads' => 'Total Threads',
    'new_members' => 'New Members',
    'categories' => 'Categories',
    'tags' => 'Tags',
    'filters' => 'Filters',
    'sort_by' => 'Sort By',
    'date_created' => 'Date Created',
    'last_updated' => 'Last Updated',
    'most_viewed' => 'Most Viewed',
    'most_liked' => 'Most Liked',
    'most_replied' => 'Most Replied',
    'load_more' => 'Load More',
    'show_more' => 'Show More',
    'show_less' => 'Show Less',
    'read_more' => 'Read More',
    'read_less' => 'Read Less',
    'share' => 'Share',
    'bookmark' => 'Bookmark',
    'report' => 'Report',
    'subscribe' => 'Subscribe',
    'unsubscribe' => 'Unsubscribe',
    'follow' => 'Follow',
    'unfollow' => 'Unfollow',
    'like' => 'Like',
    'unlike' => 'Unlike',
    'comment' => 'Comment',
    'reply' => 'Reply',
    'quote' => 'Quote',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'restore' => 'Restore',
    'archive' => 'Archive',
    'pin' => 'Pin',
    'unpin' => 'Unpin',
    'lock' => 'Lock',
    'unlock' => 'Unlock',
    'approve' => 'Approve',
    'reject' => 'Reject',
    'pending' => 'Pending',
    'published' => 'Published',
    'draft' => 'Draft',
    'private' => 'Private',
    'public' => 'Public',
    'featured' => 'Featured',
    'sticky' => 'Sticky',
    'closed' => 'Closed',
    'open' => 'Open',
    'solved' => 'Solved',
    'unsolved' => 'Unsolved',
    'verified' => 'Verified',
    'unverified' => 'Unverified',
    'or' => 'or',
    'and' => 'and',
    'processing' => 'Processing...',
    'error_occurred' => 'An error occurred. Please try again.',
    'new_message' => 'New Message',
    'minimize' => 'Minimize',
    'list' => 'List',
    'chat' => 'Chat',
    'showcase_item' => 'Showcase Item',
    'welcome' => 'Welcome',
    'logged_in_message' => 'You\'re logged in!',
    'knowledge_hub' => 'Mechanical Knowledge Hub',
    'connect_engineers' => 'Connect with 64+ professional engineers',
    'join_discussions' => 'Join 118+ technical discussions',
    'share_experience' => 'Share CAD/CAM/CNC experience',
    'join_engineering_community' => 'Join the leading mechanical engineering community',
    'featured_topics' => 'Featured Topics',
    'no_featured_topics' => 'No featured topics yet',
    'view_more' => 'View More',
    'view_all' => 'View All',
    'popular_forums' => 'Popular Forums',
    'no_forums' => 'No forums yet',
    'active_members' => 'Active Members',
    'contributions' => 'contributions',
    'no_active_members' => 'No active members yet',
    'related_communities' => 'Related Communities',
    'topics' => 'topics',
    'topic' => 'topic',
    'mechamap_community' => 'MechaMap Community',
    'professional_network' => 'Professional Engineering Network',
    'technical_discussions' => 'Technical Discussions',
    'engineers' => 'Engineers',
    'weekly_activity' => 'Weekly Activity',
    'growth_rate' => 'Growth Rate',
    'join_professional_network' => 'Join Professional Network',
    'weekly_trends' => 'Weekly Trends',
    'points' => 'points',
    'discussions' => 'discussions',
    'featured_discussions' => 'Featured Discussions',
    'in' => 'in',
    'top_engineers' => 'Top Engineers',
    'leaderboard' => 'Leaderboard',
    'recently' => 'recently',
    'recommendations_for_you' => 'Recommendations for You',
    'by' => 'by',
    'active_forums' => 'Active Forums',
    'new_this_month' => 'new this month',
    'high_activity' => 'High Activity',
    'medium_activity' => 'Medium Activity',
    'low_activity' => 'Low Activity',
];
