<?php

/**
 * English translations for ui/forms
 * Form elements and validation
 * 
 * Structure: ui.forms.*
 * Populated: 2025-07-20 02:32:30
 * Keys: 110
 */

return [
    'labels' => [
        'name' => 'Name',
        'email' => 'Email',
        'password' => 'Password',
        'confirm_password' => 'Confirm Password',
        'username' => 'Username',
        'phone' => 'Phone',
        'address' => 'Address',
        'city' => 'City',
        'country' => 'Country',
        'title' => 'Title',
        'description' => 'Description',
        'content' => 'Content',
        'category' => 'Category',
        'tags' => 'Tags',
        'image' => 'Image',
        'file' => 'File',
        'date' => 'Date',
        'time' => 'Time',
        'status' => 'Status',
        'priority' => 'Priority',
        'type' => 'Type',
        'subject' => 'Subject',
        'message' => 'Message',
        'comment' => 'Comment',
        'reply' => 'Reply',
        'search' => 'Search',
        'filter' => 'Filter',
        'sort' => 'Sort',
    ],
    'placeholders' => [
        'enter_name' => 'Enter name',
        'enter_email' => 'Enter email address',
        'enter_password' => 'Enter password',
        'enter_username' => 'Enter username',
        'enter_phone' => 'Enter phone number',
        'enter_title' => 'Enter title',
        'enter_description' => 'Enter description',
        'enter_content' => 'Enter content',
        'search_placeholder' => 'Search...',
        'select_category' => 'Select category',
        'select_option' => 'Select option',
        'enter_tags' => 'Enter tags (comma separated)',
        'enter_comment' => 'Enter your comment...',
        'enter_message' => 'Enter your message...',
    ],
    'validation' => [
        'required' => 'This field is required',
        'email' => 'Invalid email address',
        'min_length' => 'Minimum :min characters',
        'max_length' => 'Maximum :max characters',
        'confirmed' => 'Confirmation does not match',
        'unique' => 'This value already exists',
        'numeric' => 'Must be a number',
        'file_size' => 'File size too large',
        'file_type' => 'File type not supported',
        'image' => 'Must be an image file',
        'url' => 'Invalid URL',
        'date' => 'Invalid date',
        'password_strength' => 'Password must be at least 8 characters with uppercase, lowercase and numbers',
    ],
    'help' => [
        'password_requirements' => 'Password must be at least 8 characters',
        'username_requirements' => 'Username can only contain letters, numbers and underscores',
        'email_verification' => 'We will send a verification email to this address',
        'optional_field' => 'Optional field',
        'required_field' => 'Required field',
        'file_upload' => 'Select file to upload',
        'image_upload' => 'Select image (JPG, PNG, GIF)',
        'max_file_size' => 'Maximum size: :size MB',
    ],
    'states' => [
        'loading' => 'Loading...',
        'saving' => 'Saving...',
        'saved' => 'Saved',
        'error' => 'Error occurred',
        'success' => 'Success',
        'uploading' => 'Uploading...',
        'uploaded' => 'Uploaded',
        'processing' => 'Processing...',
        'completed' => 'Completed',
    ],
    'actions' => [
        'submit' => 'Submit',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'reset' => 'Reset',
        'clear' => 'Clear',
        'upload' => 'Upload',
        'download' => 'Download',
        'preview' => 'Preview',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'add' => 'Add',
        'remove' => 'Remove',
        'select' => 'Select',
        'deselect' => 'Deselect',
        'select_all' => 'Select All',
        'deselect_all' => 'Deselect All',
    ],
    'upload' => [
        'drag_drop_here' => 'Drag and drop files here',
        'or' => 'or',
        'select_from_computer' => 'select from computer',
        'select_files' => 'Select Files',
        'attach_file' => 'Attach File',
        'attach_files' => 'Attach Files',
        'attach_images_optional' => 'Attach images (optional)',
        'optional' => 'optional',
        'supported_formats' => 'Supported: JPG, PNG, GIF (max :size MB per file)',
        'supported_formats_with_size' => 'Supported formats: :formats (max :size per file)',
        'files_selected' => 'Selected Files',
        'uploading' => 'Uploading...',
        'upload_complete' => 'Upload Complete',
        'file_too_large' => 'File \":filename\" is too large',
        'file_type_not_supported' => 'File \":filename\" is not supported',
        'max_files_exceeded' => 'Maximum number of files exceeded',
        'add_quote' => 'Add Quote',
        'quote' => 'Quote',
    ],
    'related' => [
        'related_topics' => 'Related Topics',
    ],
    'required' => 'Required',
    'optional' => 'Optional',
    'placeholder' => [
        'search' => 'Enter search keywords...',
        'email' => 'Enter your email',
        'password' => 'Enter password',
    ],
];
